const AdditionalInformation = {
  Id: 1,
  Name: "Additional Information",
  QuestionCount: 11,
  EntityType: "PersonalDetails",
  Questions: [
    {
      CategoryDesc: "Additional Information",
      AnswerChoices: ["Yes", "No"],
      AnswerChoices_KN: ["ಹೌದು", "ಇಲ್ಲ"],


      CategoryName: "Additional Information",
      DisplaySequence: 170,
      Id: 170,
      QText: "Does your natal family accept your chosen gender?",
      QText_KN: "ನಿಮ್ಮ ಜನ್ಮಸ್ಥಳ ಕುಟುಂಬವು ನೀವು ಆಯ್ಕೆ ಮಾಡಿದ ಲಿಂಗವನ್ನು ಸ್ವೀಕರಿಸುತ್ತದೆಯೇ?",
      QuestionId: 170,
      QuestionPaperId: 170,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Additional Information",
      SubCategoryName: "Additional Information",
    },
    {
      CategoryDesc: "Additional Information",
      AnswerChoices: ["Yes", "No"],
      AnswerChoices_KN: ["ಹೌದು", "ಇಲ್ಲ"],
  CategoryName: "Additional Information",
      DisplaySequence: 171,
      Id: 171,
      QText: "If No, do you have contact with them?",
      QText_KN: "ಇಲ್ಲದಿದ್ದರೆ, ನೀವು ಅವರೊಂದಿಗೆ ಸಂಪರ್ಕವನ್ನು ಹೊಂದಿಲ್ಲ?",
      QuestionId: 171,
      QuestionPaperId: 171,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Additional Information",
      SubCategoryName: "Additional Information",
    },
    {
      AdditionalComment: false,
      AnswerChoices: ["Yes", "No"],
      AnswerChoices_KN: ["ಹೌದು", "ಇಲ್ಲ"],

      CategoryDesc: "Additional Information",
      CategoryName: "Additional Information",
      DisplaySequence: 172,
      Id: 172,
      QText:
        "Do you head any organization working for transgender in Karnataka?",
        QText_KN: "ಕರ್ನಾಟಕದಲ್ಲಿ ಟ್ರಾನ್ಸ್‌ಜೆಂಡರ್‌ಗಾಗಿ ಕೆಲಸ ಮಾಡುವ ಯಾವುದೇ ಸಂಸ್ಥೆಯ ಮುಖ್ಯಸ್ಥರಾಗಿದ್ದೀರಾ?",
      QuestionId: 172,
      QuestionPaperId: 172,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Additional Information",
      SubCategoryName: "Additional Information",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [],
      CategoryDesc: "Additional Information",
      CategoryName: "Additional Information",
      DisplaySequence: 173,
      Id: 173,
      QText: "If Yes, name the organization ",
      QText_KN: "ಹೌದು ಎಂದಾದರೆ ಸಂಸ್ಥೆಯನ್ನು ಹೆಸರಿಸಿ",
      QuestionId: 173,
      QuestionPaperId: 173,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Additional Information",
      SubCategoryName: "Additional Information",
    },
    {
      AdditionalComment:true,
      AdditionalQuestion:"If Others, specify",
      AnswerChoices: ["Music",
        "Dance",
        "Theatre",
        "Mimicry",
        "Public oration",
        "Cinema",
        "Modeling",
        "Others"  ],
        AnswerChoices_KN: ["ಸಂಗೀತ",
        "ನೃತ್ಯ",
        "ರಂಗಭೂಮಿ",
        "ಮಿಮಿಕ್ರಿ",
        "ಸಾರ್ವಜನಿಕ ಭಾಷಣ",
        "ಸಿನೆಮಾ",
        "ಮಾಡೆಲಿಂಗ್",
        "ಇತರೆ"  ],
      CategoryDesc: "Additional Information",
      CategoryName: "Additional Information",
      DisplaySequence: 174,
      Id: 174,
      QText: "Do you have any cultural flair?",
      QText_KN: "ನೀವು ಯಾವುದೇ ಸಾಂಸ್ಕೃತಿಕ ಮೇಳವನ್ನು ಹೊಂದಿದ್ದೀರಾ?",
      QuestionId: 174,
      QuestionPaperId: 174,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Additional Information",
      SubCategoryName: "Additional Information",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [],
      CategoryDesc: "Education Details",
      CategoryName: "Education Details",
      DisplaySequence: 175,
      Id: 175,
      QText: "If Others, specify",
        QText_KN:"ಇತರೆಯಾದಲ್ಲಿ, ಸ್ಪಷ್ಟವಾಗಿ ನಮೂದಿಸಿ",
      QuestionId: 175,
      QuestionPaperId: 175,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Additional Information",
      SubCategoryName: "Additional Information",
    },
    {
      AdditionalComment: false,
      AnswerChoices: ["Yes", "No"],
      AnswerChoices_KN: ["ಹೌದು", "ಇಲ್ಲ"],
      CategoryDesc: "Additional Information",
      CategoryName: "Additional Information",
      DisplaySequence: 176,
      Id: 176,
      QText: "Do you think sex work is a profession?",
      QText_KN: "ಲೈಂಗಿಕ ಕೆಲಸವು ಒಂದು ವೃತ್ತಿ ಎಂದು ನೀವು ಭಾವಿಸುತ್ತೀರಾ?",
      QuestionId: 176,
      QuestionPaperId: 176,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Additional Information",
      SubCategoryName: "Additional Information",
    },

    {
      AdditionalComment: false,
      AnswerChoices: ["Yes", "No"],
      AnswerChoices_KN: ["ಹೌದು", "ಇಲ್ಲ"],
      CategoryDesc: "Additional Information",
      CategoryName: "Additional Information",
      DisplaySequence: 177,
      Id: 177,
      QText:
        "Do you think Mankti (blessing and receiving money as Hijaras)is a profession?",
        QText_KN: "ಮಂಕ್ತಿ (ಹಿಜಾರಾಗಳಂತೆ ಆಶೀರ್ವಾದ ಮತ್ತು ಹಣವನ್ನು ಸ್ವೀಕರಿಸುವುದು) ಒಂದು ವೃತ್ತಿ ಎಂದು ನೀವು ಭಾವಿಸುತ್ತೀರಾ?",
      QuestionId: 177,
      QuestionPaperId: 177,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Additional Information",
      SubCategoryName: "Additional Information",
    },
    {
      AdditionalComment: false,
      AnswerChoices: ["Yes", "No"],
      AnswerChoices_KN: ["ಹೌದು", "ಇಲ್ಲ"],
      CategoryDesc: "Additional Information",
      CategoryName: "Additional Information",
      DisplaySequence: 178,
      Id: 178,
      QText:
        "Do you think that Karnataka police systems and other departments need to be sensitized about transgenders?",
        QText_KN: "ಕರ್ನಾಟಕ ಪೊಲೀಸ್ ವ್ಯವಸ್ಥೆಗಳು ಮತ್ತು ಇತರ ಇಲಾಖೆಗಳು ಟ್ರಾನ್ಸ್‌ಜೆಂಡರ್‌ಗಳ ಬಗ್ಗೆ ಸಂವೇದನಾಶೀಲರಾಗಬೇಕು ಎಂದು ನೀವು ಭಾವಿಸುತ್ತೀರಾ?",
      QuestionId: 178,
      QuestionPaperId: 178,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Additional Information",
      SubCategoryName: "Additional Information",
    },
    {
      AdditionalComment: true,
      AdditionalQuestion:"If Others, specify",
      AnswerChoices: ["Financial",
        "Physical",
        "Emotional",
        "Mental",
        "Cultural",
        "Social",
        "Political",
        "Others" ],
        AnswerChoices_KN: ["ಹಣಕಾಸು",
        "ಭೌತಿಕ",
        "ಭಾವನಾತ್ಮಕ",
        "ಮಾನಸಿಕ",
        "ಸಾಂಸ್ಕೃತಿಕ",
        "ಸಾಮಾಜಿಕ",
        "ರಾಜಕೀಯ",
        "ಇತರೆ"  ],
      CategoryDesc: "Additional Information",
      CategoryName: "Additional Information",
      DisplaySequence: 179,
      Id: 179,
      QText:
        "To be equal with other citizens of this country what support do you need?",
        QText_KN: "ಈ ದೇಶದ ಇತರ ನಾಗರಿಕರೊಂದಿಗೆ ಸಮಾನವಾಗಿರಲು ನಿಮಗೆ ಯಾವ ಬೆಂಬಲ ಬೇಕು?",
      QuestionId: 179,
      QuestionPaperId: 179,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Additional Information",
      SubCategoryName: "Additional Information ",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [],
      CategoryDesc: "Additional Information",
      CategoryName: "Additional Information",
      DisplaySequence: 180,
      Id: 180,
      QText: "If Others, specify",
        QText_KN:"ಇತರೆಯಾದಲ್ಲಿ, ಸ್ಪಷ್ಟವಾಗಿ ನಮೂದಿಸಿ",
      QuestionId: 180,
      QuestionPaperId: 180,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Additional Information ",
      SubCategoryName: "Additional Information ",
    },
  ],
};

export default AdditionalInformation;