const AdditionalInformation = {
  Id: 80,
  Name: "Additional Information",
  QuestionCount: 11,
  Questions: [
    {
      AdditionalComment: false,
      AnswerChoices: [
        { AText: "Yes", Id: 5533 },
        { AText: "No", Id: 5534 },
      ],
      CategoryDesc: "EDCS",
      CategoryName: "Karmani V0.1",
      DisplaySequence: 1,
      Id: 2257,
      QText: "Does your natal family accept your chosen gender ",
      QuestionId: 500,
      QuestionPaperId: 80,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Additional Information",
      SubCategoryName: "7.Additional Information",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [
        { AText: "Yes", Id: 5531 },
        { AText: "No", Id: 5532 },
      ],
      CategoryDesc: "EDCS",
      CategoryName: "Karmani V0.1",
      DisplaySequence: 2,
      Id: 2256,
      QText: "If your do not family accept, do you have contact with them ",
      QuestionId: 306,
      QuestionPaperId: 80,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Additional Information",
      SubCategoryName: "7.Additional Information",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [
        { AText: "Yes", Id: 5535 },
        { AText: "No", Id: 5536 },
      ],
      CategoryDesc: "EDCS",
      CategoryName: "Karmani V0.1",
      DisplaySequence: 3,
      Id: 2258,
      QText:
        "Do you head any organization working for Transgender in Karnataka ",
      QuestionId: 522,
      QuestionPaperId: 80,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Additional Information",
      SubCategoryName: "7.Additional Information",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [],
      CategoryDesc: "EDCS",
      CategoryName: "Karmani V0.1",
      DisplaySequence: 4,
      Id: 2264,
      QText:
        "If yes, name the organization working for Transgender in Karnataka ",
      QuestionId: 526,
      QuestionPaperId: 80,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Additional Information",
      SubCategoryName: "7.Additional Information",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [
        { AText: "Music", Id: 5537 },
        { AText: "Dance", Id: 5538 },
        { AText: "Theatre", Id: 5539 },
        { AText: "Mimicry", Id: 5540 },
        { AText: "Public Oration", Id: 5541 },
        { AText: "Cinema", Id: 5542 },
        { AText: "Modeling", Id: 5543 },
        { AText: "Others", Id: 5544 },
      ],
      CategoryDesc: "EDCS",
      CategoryName: "Karmani V0.1",
      DisplaySequence: 5,
      Id: 2259,
      QText: "Do you have any cultural flair: ",
      QuestionId: 528,
      QuestionPaperId: 80,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Additional Information",
      SubCategoryName: "7.Additional Information",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [],
      CategoryDesc: "EDCS",
      CategoryName: "Karmani V0.1",
      DisplaySequence: 6,
      Id: 2265,
      QText: "If Others Cultural flair,specify",
      QuestionId: 532,
      QuestionPaperId: 80,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Additional Information",
      SubCategoryName: "7.Additional Information",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [
        { AText: "Yes", Id: 5545 },
        { AText: "No", Id: 5546 },
      ],
      CategoryDesc: "EDCS",
      CategoryName: "Karmani V0.1",
      DisplaySequence: 7,
      Id: 2260,
      QText: "Do you think sex work is a profession ",
      QuestionId: 530,
      QuestionPaperId: 80,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Additional Information",
      SubCategoryName: "7.Additional Information",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [
        { AText: "Yes", Id: 5547 },
        { AText: "No", Id: 5548 },
      ],
      CategoryDesc: "EDCS",
      CategoryName: "Karmani V0.1",
      DisplaySequence: 8,
      Id: 2261,
      QText:
        "Do you think Mankti (blessing and receiving money as Hijras) is a profession ",
      QuestionId: 534,
      QuestionPaperId: 80,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Additional Information",
      SubCategoryName: "7.Additional Information",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [
        { AText: "Yes", Id: 5549 },
        { AText: "No", Id: 5550 },
      ],
      CategoryDesc: "EDCS",
      CategoryName: "Karmani V0.1",
      DisplaySequence: 9,
      Id: 2262,
      QText:
        "Do you think that Karnataka Police systems and other deparments need to be sensitized about transgenders ",
      QuestionId: 535,
      QuestionPaperId: 80,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Additional Information",
      SubCategoryName: "7.Additional Information",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [
        { AText: "Financial", Id: 5551 },
        { AText: "Physical", Id: 5552 },
        { AText: "Emotional", Id: 5553 },
        { AText: "Mental", Id: 5554 },
        { AText: "Cultural", Id: 5555 },
        { AText: "Social", Id: 5556 },
        { AText: "Political", Id: 5557 },
        { AText: "Others", Id: 5558 },
      ],
      CategoryDesc: "EDCS",
      CategoryName: "Karmani V0.1",
      DisplaySequence: 10,
      Id: 2263,
      QText:
        "To be equal with other citizens of this country what support do you need: ",
      QuestionId: 536,
      QuestionPaperId: 80,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Additional Information",
      SubCategoryName: "7.Additional Information",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [],
      CategoryDesc: "EDCS",
      CategoryName: "Karmani V0.1",
      DisplaySequence: 11,
      Id: 2266,
      QText: "If Others support needed,specify",
      QuestionId: 539,
      QuestionPaperId: 80,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Additional Information",
      SubCategoryName: "7.Additional Information",
    },
  ],
};
export default AdditionalInformation;
