const Education = {
  Id: 1,
  Name: "Education Details",
  QuestionCount: 29,
  EntityType: "Education Details",
  Questions: [
    {
      AdditionalComment:true,
      CategoryDesc: "Education Details",
      AdditionalQuestion:"If Others, specify",
      AnswerChoices: ["Illiterate", "Literate", "Primary(1-26)",
      "Middle-6-7",
      "High School(9-10)",
      "SSLC Pass",
      "Pre Graduation Pass",
      "Cetificate courses",
      "Diploma",
      "Normal Degree(B.A/B.com/B.sc)",
      "Law DegreeTechnical Degree",
      "Technical Degree",
      "Post Graduation (Technical,Agriculture and Animal Husbandry,Others)",
      "Post Graduation- General(M.A,M.com,M.sc)",
      "MBBS",
      "BDS",
      "Ayurveda",
      "MD/MS/MDS",
      "PHD",
      "ME/MTech/MS/MCH",
      "MBA/MCA",
      "Others"],
      AnswerChoices_KN: ["ಅನಕ್ಷರಸ್ಥ", 
      "ಅಕ್ಷರಸ್ಥ", 
      "ಪ್ರಾಥಮಿಕ(1-5)",
      "ಮಧ್ಯಮ(6-8)",
      "ಪ್ರೌಢಶಾಲೆ(9-10)",
      "SSLC ತೇರ್ಗಡೆ",
      "ಪದವಿ ಪೂರ್ವ ಪಾಸ್",
      "ಪ್ರಮಾಣಪತ್ರ ಕೋರ್ಸ್‌ಗಳು",
      "ಡಿಪ್ಲೊಮಾ",
      "ಸಾಮಾನ್ಯ ಪದವಿ(B.A/B.com/B.sc)",
      "ಕಾನೂನು ಪದವಿ",
      "ತಾಂತ್ರಿಕ ಪದವಿ",
      "ಸ್ನಾತಕೋತ್ತರ ಪದವಿ (ತಾಂತ್ರಿಕ, ಕೃಷಿ ಮತ್ತು ಪಶುಸಂಗೋಪನೆ, ಇತರೆ)",
      "ಸ್ನಾತಕೋತ್ತರ ಪದವಿ- ಸಾಮಾನ್ಯ (M.A,M.com,M.sc)",
      "ಎಂಬಿಬಿಎಸ್",
      "ಬಿಡಿಎಸ್",
      "ಆಯುರ್ವೇದ",
      "MD/MS/MDS",
      "PHD",
      "ME/MTech/MS/MCH",
      "MBA/MCA",
      "ಇತರೆ"],
      CategoryName: "Education Details",
      DisplaySequence: 24,
      Id: 24,
      QText: "Education Qualification (formal)",
      QText_KN: "ಶಿಕ್ಷಣ ಅರ್ಹತೆ (ಔಪಚಾರಿಕ)",
      QuestionId: 24,
      QuestionPaperId: 24,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Education Details",
      SubCategoryName: "Education Details",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [],
      CategoryDesc: "Education Details",
      CategoryName: "Education Details",
      DisplaySequence: 25,
      Id: 25,
      QText: "If Others, specify",
        QText_KN:"ಇತರೆಯಾದಲ್ಲಿ, ಸ್ಪಷ್ಟವಾಗಿ ನಮೂದಿಸಿ",
      QuestionId: 25,
      QuestionPaperId: 25,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Education Details",
      SubCategoryName: "Education Details",
    },
    {
      AdditionalComment: true,
      AdditionalQuestion:"If Others, specify",
      AnswerChoices: [
        "Corporation school",
        "Government school",
        "Private school",
        "Convent",
        "Others",
      ],
      AnswerChoices_KN: [
        "ಕಾರ್ಪೊರೇಷನ್ ಶಾಲೆ",
        "ಸರ್ಕಾರಿ ಶಾಲೆ",
        "ಖಾಸಗಿ ಶಾಲೆ",
        "ಕಾನ್ವೆಂಟ್",
        "ಇತರೆ",
      ],
      CategoryDesc: "Education Details",
      CategoryName: "Education Details",
      DisplaySequence: 26,
      Id: 26,
      QText: "Did you study in ",
      QText_KN: " ಇತರೆಯಾದಲ್ಲಿ, ಸ್ಪಷ್ಟವಾಗಿ ನಮೂದಿಸಿ",
      QuestionId: 26,
      QuestionPaperId: 26,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Personal Details",
      SubCategoryName: "Personal Details",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [],
      CategoryDesc: "Education Details",
      CategoryName: "Education Details",
      DisplaySequence: 27,
      Id: 27,
      QText: "If Others, specify",
        QText_KN:"ಇತರೆಯಾದಲ್ಲಿ, ಸ್ಪಷ್ಟವಾಗಿ ನಮೂದಿಸಿ್",
      QuestionId: 27,
      QuestionPaperId: 27,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Education Details",
      SubCategoryName: "Education Details",
    },
    {
      AdditionalComment: false,
      AnswerChoices: ["Yes", "No"],
      AnswerChoices_KN: ["ಹೌದು", "ಇಲ್ಲ"],
      CategoryDesc: "Education Details",
      CategoryName: "Education Details",
      DisplaySequence: 28,
      Id: 28,
      QText: "Have you received any training in skills?",
      QText_KN: "ನೀವು ಕೌಶಲ್ಯದಲ್ಲಿ ಯಾವುದೇ ತರಬೇತಿ ಪಡೆದಿದ್ದೀರಾ?",
      QuestionId: 28,
      QuestionPaperId: 28,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Education Details",
      SubCategoryName: "Education Details",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [
        "Hand Embroidery", 
      "Domestic Data Entry Operator",
      "Self Employed Tailor",
      "Accounts Executive- Accounts Payable and Receivable",
      "Customer Care Executive - Relationship Centre",
      "Field Technician Computing and Peripherals",
      "Retail Sales Associate",
      "Telecom -In-store promoter",
      "Sewing Machine Operator",
      "Assistant Beauty Therapist",
      "CNC Operator Turning",
      "Fitness Trainer",
      "Life Insurance Agent",
      "Micro Finance Executive",
      "Small and Medium Enterprise Officer",
      "CCTV Installation Technician",
      "Pedicurist & Manicurist",
      "Mobile Phone Hardware Repair Technician",
      "TV Repair Technician",
      "Beauty Therapist",
      "Hair Stylist",
      "Retail Sales Associate",
      "Animator",
      "Junior Software Developer"

    ],
    AnswerChoices_KN: [
      "ಕೈ ಕಸೂತಿ", 
    "ದೇಶೀಯ ಡೇಟಾ ಎಂಟ್ರಿ ಆಪರೇಟರ್",
    "ಸ್ವಯಂ ಉದ್ಯೋಗದ ಟೈಲರ್",
    "ಅಕೌಂಟ್ಸ್ ಎಕ್ಸಿಕ್ಯೂಟಿವ್- ಪಾವತಿಸಬೇಕಾದ ಮತ್ತು ಸ್ವೀಕರಿಸಬಹುದಾದ ಖಾತೆಗಳು",
    "ಕಸ್ಟಮರ್ ಕೇರ್ ಎಕ್ಸಿಕ್ಯೂಟಿವ್ - ಸಂಬಂಧ ಕೇಂದ್ರ",
    "ಫೀಲ್ಡ್ ಟೆಕ್ನಿಷಿಯನ್ ಕಂಪ್ಯೂಟಿಂಗ್ ಮತ್ತು ಪೆರಿಫೆರಲ್ಸ್",
    "ಕ್ಷೇತ್ರ ತಂತ್ರಜ್ಞ ನೆಟ್‌ವರ್ಕಿಂಗ್ ಮತ್ತು ಸಂಗ್ರಹಣೆ",
    "ರಿಟೇಲ್ ಸೇಲ್ಸ್ ಅಸೋಸಿಯೇಟ್",
    "ಟೆಲಿಕಾಂ -ಇನ್-ಸ್ಟೋರ್ ಪ್ರವರ್ತಕ",
    "ಹೊಲಿಗೆ ಯಂತ್ರ ಆಪರೇಟರ್",
    "ಸಹಾಯಕ ಸೌಂದರ್ಯ ಚಿಕಿತ್ಸಕ",
    "CNC ಆಪರೇಟರ್ ಟರ್ನಿಂಗ್",
    "ಫಿಟ್ನೆಸ್ ತರಬೇತುದಾರ",
    "ಜೀವ ವಿಮಾ ಏಜೆಂಟ್",
    "ಮೈಕ್ರೋ ಫೈನಾನ್ಸ್ ಎಕ್ಸಿಕ್ಯೂಟಿವ್",
    "ಸಣ್ಣ ಮತ್ತು ಮಧ್ಯಮ ಉದ್ದಿಮೆ ಅಧಿಕಾರಿ",
    "CCTV ಅಳವಡಿಕೆ ತಂತ್ರಜ್ಞ",
    "ಪಾದೋಪಚಾರ ಮತ್ತು ಹಸ್ತಾಲಂಕಾರಕಾರ",
    "ಮೊಬೈಲ್ ಫೋನ್ ಹಾರ್ಡ್‌ವೇರ್ ರಿಪೇರಿ ತಂತ್ರಜ್ಞ",
    "ಟಿವಿ ರಿಪೇರಿ ತಂತ್ರಜ್ಞ",
    "ಸೌಂದರ್ಯ ಚಿಕಿತ್ಸಕ",
    "ಹೇರ್ ಸ್ಟೈಲಿಸ್ಟ್",
    "ರಿಟೇಲ್ ಸೇಲ್ಸ್ ಅಸೋಸಿಯೇಟ್",
    "ಆನಿಮೇಟರ್",
    "ಜೂನಿಯರ್ ಸಾಫ್ಟ್‌ವೇರ್ ಡೆವಲಪರ್"
  ],
      CategoryDesc: "Education Details",
      CategoryName: "Education Details",
      DisplaySequence: 29,
      Id: 29,
      QText: "If Yes, what skill?",
      QText_KN: "ಹೌದಾದರೆ ಏನು ಕೌಶಲ್ಯ",
      QuestionId: 29,
      QuestionPaperId: 29,
      QuestionTypeName: "Multiple Select",
      SubCategoryDesc: "Education Details",
      SubCategoryName: "Education Details",
    },
    {
      AdditionalComment: false,
      AnswerChoices: ["NA", 1, 2,3],
      AnswerChoices_KN: ["NA", 1, 2,3],
      CategoryDesc: "Education Details",
      CategoryName: "Education Details",
      DisplaySequence: 30,
      Id: 30,
      QText: "How many days/months/years of training did you receive?",
      QText_KN: "ನೀವು ಎಷ್ಟು ದಿನಗಳು/ತಿಂಗಳು/ವರ್ಷಗಳ ತರಬೇತಿಯನ್ನು ಪಡೆದಿದ್ದೀರಿ?",
      QuestionId: 30,
      QuestionPaperId: 30,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Education Details",
      SubCategoryName: "Education Details",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [],
      CategoryDesc: "Education Details",
      CategoryName: "Education Details",
      DisplaySequence: 31,
      Id: 31,
      QText: "From where did you get the skill training?",
      QText_KN: "ಕೌಶಲ್ಯ ತರಬೇತಿಯನ್ನು ಎಲ್ಲಿಂದ ಪಡೆದರು?",
      QuestionId: 31,
      QuestionPaperId: 31,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Education Details",
      SubCategoryName: "Education Details",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [        "Hand Embroidery", 
      "Domestic Data Entry Operator",
      "Self Employed Tailor",
      "Accounts Executive- Accounts Payable and Receivable",
      "Customer Care Executive - Relationship Centre",
      "Field Technician Computing and Peripherals",
      "Retail Sales Associate",
      "Telecom -In-store promoter",
      "Sewing Machine Operator",
      "Assistant Beauty Therapist",
      "CNC Operator Turning",
      "Fitness Trainer",
      "Life Insurance Agent",
      "Micro Finance Executive",
      "Small and Medium Enterprise Officer",
      "CCTV Installation Technician",
      "Pedicurist & Manicurist",
      "Mobile Phone Hardware Repair Technician",
      "TV Repair Technician",
      "Beauty Therapist",
      "Hair Stylist",
      "Retail Sales Associate",
      "Animator",
      "Junior Software Developer"
],
AnswerChoices_KN: [      "ಕೈ ಕಸೂತಿ",
"ಡೊಮೆಸ್ಟಿಕ್ ಡಾಟಾ ಎಂಟ್ರಿ ಆಪರೇಟರ್",
"ಸ್ವಯಂ ಉದ್ಯೋಗಿ ಟೈಲರ್",
"ಖಾತೆಗಳ ಕಾರ್ಯನಿರ್ವಾಹಕ- ಪಾವತಿಸಬೇಕಾದ ಮತ್ತು ಸ್ವೀಕರಿಸಬಹುದಾದ ಖಾತೆ",
"ಕಸ್ಟಮರ್ ಕೇರ್ ಎಕ್ಸಿಕ್ಯೂಟಿವ್ - ಸಂಬಂಧ ಕೇಂದ್ರ",
"ಫೀಲ್ಡ್ ಟೆಕ್ನಿಷಿಯನ್ ಕಂಪ್ಯೂಟಿಂಗ್ ಮತ್ತು ಪೆರಿಫೆರಲ್ಸ್",
"ರೀಟೇಲ್ ಸೇಲ್ಸ್ ಅಸೋಸಿಯೇಟ್",
"ಟೆಲಿಕಾಂ-ಇನ್-ಸ್ಟೋರ್ ಪ್ರವರ್ತಕ",
"ಹೊಲಿಗೆ ಯಂತ್ರ ಆಪರೇಟರ್",
"ಸಹಾಯಕ ಬ್ಯೂಟಿ ಥೆರಪಿಸ್ಟ್",
"CNC ಆಪರೇಟರ್ ಟರ್ನಿಂಗ್",
"ಫಿಟ್ನೆಸ್ ತರಬೇತುದಾರ",
"ಜೀವ ವಿಮಾ ಏಜೆಂಟ್",
"ಮೈಕ್ರೋ ಫೈನಾನ್ಸ್ ಎಕ್ಸಿಕ್ಯೂಟಿವ್",
"ಸಣ್ಣ ಮತ್ತು ಮಧ್ಯಮ ಉದ್ಯಮ ಅಧಿಕಾರಿ",
"CCTV ಅಳವಡಿಕೆ ತಂತ್ರಜ್ಞ",
"ಪಾದೋಪಚಾರ ಮತ್ತು ಹಸ್ತಾಲಂಕಾರಕಾರ",
"ಮೊಬೈಲ್ ಫೋನ್ ಹಾರ್ಡ್‌ವೇರ್ ರಿಪೇರಿ ತಂತ್ರಜ್ಞ",
"ಟಿವಿ ರಿಪೇರಿ ತಂತ್ರಜ್ಞ",
"ಸೌಂದರ್ಯ ಚಿಕಿತ್ಸಕ",
"ಕೇಶ ವಿನ್ಯಾಸಕಿ",
"ರೀಟೇಲ್ ಸೇಲ್ಸ್ ಅಸೋಸಿಯೇಟ್",
"ಆನಿಮೇಟರ್",
"ಜೂನಿಯರ್ ಸಾಫ್ಟ್‌ವೇರ್ ಡೆವಲಪರ್"
],
      CategoryDesc: "Education Details",
      CategoryName: "Education Details",
      DisplaySequence: 32,
      Id: 32,
      QText: "What skill would you like to acquire?",
      QText_KN: "ನೀವು ಯಾವ ಕೌಶಲ್ಯವನ್ನು ಪಡೆಯಲು ಬಯಸುತ್ತೀರಿ?",
      QuestionId: 32,
      QuestionPaperId: 32,
      QuestionTypeName: "Multiple Select",
      SubCategoryDesc: "Education Details",
      SubCategoryName: "Education Details",
    },
    {
      AdditionalComment: false,
      AnswerChoices: ["Yes", "No"],
      AnswerChoices_KN: ["ಹೌದು", "ಇಲ್ಲ"],
      CategoryDesc: "Education Details",
      CategoryName: "Education Details",
      DisplaySequence: 33,
      Id: 33,
      QText: "Did you receive any informal education?",
      QText_KN: "ನೀವು ಯಾವುದೇ ಅನೌಪಚಾರಿಕ ಶಿಕ್ಷಣವನ್ನು ಪಡೆದಿದ್ದೀರಾ?",
      QuestionId: 33,
      QuestionPaperId: 33,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Education Details",
      SubCategoryName: "Education Details",
    },
    {
      AdditionalComment: true,
      AdditionalQuestion:"If Others, specify",
      AnswerChoices: ["Community-based organization", "Friends", "Others"],
      AnswerChoices_KN: ["ಸಮುದಾಯ ಆಧಾರಿತ ಸಂಸ್ಥೆಗಳು", " ಸ್ನೇಹಿತರು", "ಇತರೆ"],
      CategoryDesc: "Education Details",
      CategoryName: "Education Details",
      DisplaySequence: 34,
      Id: 34,
      QText: "If Yes specify",
      QText_KN: "ಹೌದು ಎಂದಾದರೆ ಸೂಚಿಸಿ",
      QuestionId: 34,
      QuestionPaperId: 34,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Education Details",
      SubCategoryName: "Education Details",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [],
      CategoryDesc: "Education Details",
      CategoryName: "Education Details",
      DisplaySequence: 35,
      Id: 35,
      QText: "If Others, specify",
        QText_KN:"ಇತರೆಯಾದಲ್ಲಿ, ಸ್ಪಷ್ಟವಾಗಿ ನಮೂದಿಸಿ",
      QuestionId: 35,
      QuestionPaperId: 35,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Education Details",
      SubCategoryName: "Education Details",
    },
    {
      AdditionalComment: false,
      AnswerChoices: ["Yes", "No"],
      AnswerChoices_KN: ["ಹೌದು", "ಇಲ್ಲ"],
      CategoryDesc: "Education Details",
      CategoryName: "Education Details",
      DisplaySequence: 36,
      Id: 36,
      QText: "Are you presently studying?",
      QText_KN: "ನೀವು ಪ್ರಸ್ತುತ ಅಧ್ಯಯನ ಮಾಡುತ್ತಿದ್ದೀರಾ?",
      QuestionId: 36,
      QuestionPaperId: 36,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Education Details",
      SubCategoryName: "Education Details",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [],
      CategoryDesc: "Education Details",
      CategoryName: "Education Details",
      DisplaySequence: 37,
      Id: 37,
      QText: "If Yes, in what class?",
      QText_KN: "ಹಾಗಿದ್ದರೆ ಯಾವ ತರಗತಿಯಲ್ಲಿ?",
      QuestionId: 37,
      QuestionPaperId: 37,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Education Details",
      SubCategoryName: "Education Details",
    },
    {
      AdditionalComment: false,
      AnswerChoices: ["Yes", "No"],
      AnswerChoices_KN: ["ಹೌದು", "ಇಲ್ಲ"],
      CategoryDesc: "Education Details",
      CategoryName: "Education Details",
      DisplaySequence: 38,
      Id: 38,
      QText: "Do you need Support for your education?",
      QText_KN: "ನಿಮ್ಮ ಶಿಕ್ಷಣಕ್ಕೆ ಬೆಂಬಲ ಬೇಕೇ?",
      QuestionId: 38,
      QuestionPaperId: 38,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Education Details",
      SubCategoryName: "Education Details",
    },
    {
      AdditionalComment: false,
      AnswerChoices: ["Yes", "No"],
      AnswerChoices_KN: ["ಹೌದು", "ಇಲ್ಲ"],
      CategoryDesc: "Education Details",
      CategoryName: "Education Details",
      DisplaySequence: 39,
      Id: 39,
      QText: "Is any Dependent in your house studying?",
      QText_KN: "ನಿಮ್ಮ ಮನೆಯಲ್ಲಿ ಯಾರಾದರೂ ಅವಲಂಬಿತರು ಓದುತ್ತಿದ್ದಾರೆಯೇ?",
      QuestionId: 39,
      QuestionPaperId: 39,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Education Details",
      SubCategoryName: "Education Details",
    },

    {
      AdditionalComment: false,
      AnswerChoices: [],
      CategoryDesc: "Education Details",
      CategoryName: "Education Details",
      DisplaySequence: 40,
      Id: 40,
      QText: "If Yes, How many people?",
      QText_KN: "ಹೌದಾದರೆ ಎಷ್ಟು ಜನ?",
      QuestionId: 40,
      QuestionPaperId: 40,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Education Details",
      SubCategoryName: "Education Details",
    },
    {
      AdditionalComment: false,
      AnswerChoices: ["Yes", "No"],
      AnswerChoices_KN: ["ಹೌದು", "ಇಲ್ಲ"],
      CategoryDesc: "Education Details",
      CategoryName: "Education Details",
      DisplaySequence: 41,
      Id: 41,
      QText: "Do they need support?",
      QText_KN: "ಅವರಿಗೆ ಬೆಂಬಲ ಬೇಕೇ?",
      QuestionId: 41,
      QuestionPaperId: 41,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Education Details",
      SubCategoryName: "Education Details",
    },
    {
      AdditionalComment: false,
      AnswerChoices: ["Yes", "No"],
      AnswerChoices_KN: ["ಹೌದು", "ಇಲ್ಲ"],
      CategoryDesc: "Education Details",
      CategoryName: "Education Details",
      DisplaySequence: 42,
      Id: 42,
      QText: "If you have discontinued education would you like to continue?",
      QText_KN: "ನೀವು ಶಿಕ್ಷಣವನ್ನು ಸ್ಥಗಿತಗೊಳಿಸಿದ್ದರೆ ನೀವು ಮುಂದುವರಿಸಲು ಬಯಸುವಿರಾ?",
      QuestionId: 42,
      QuestionPaperId: 42,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Education Details",
      SubCategoryName: "Education Details",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [],
      CategoryDesc: "Education Details",
      CategoryName: "Education Details",
      DisplaySequence: 43,
      Id: 43,
      QText: "If Yes, from which class?",
      QText_KN: "ಹಾಗಿದ್ದರೆ ಯಾವ ವರ್ಗದಿಂದ?",
      QuestionId: 43,
      QuestionPaperId: 43,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Education Details",
      SubCategoryName: "Education Details",
    },
    {
      AdditionalComment: true,
      AdditionalQuestion:"If Others, specify",
      AnswerChoices: ["Kannada", 
      "Telugu",
      "Marathi",
      "Hindi",
      "Tamil",
      "Tulu",
      "Malayalam",
      "Others"],
      AnswerChoices_KN: ["ಕನ್ನಡ", 
      "ತೆಲುಗು",
      "ಮರಾಠಿ",
      "ಹಿಂದಿ",
      "ತಮಿಳು",
      "ತುಳು",
      "ಮಲಯಾಳಂ",
      "ಇತರೆ"],
      CategoryDesc: "Education Details",
      CategoryName: "Education Details",
      DisplaySequence: 44,
      Id: 44,
      QText: "Language: Speak",
      QText_KN: "ಭಾಷೆ: ಮಾತನಾಡುವುದು",
      QuestionId: 44,
      QuestionPaperId: 44,
      QuestionTypeName: "Multiple Select",
      SubCategoryDesc: "Education Details",
      SubCategoryName: "Education Details",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [],
      CategoryDesc: "Education Details",
      CategoryName: "Education Details",
      DisplaySequence: 45,
      Id: 45,
      QText: "If Others, specify",
        QText_KN:"ಇತರೆಯಾದಲ್ಲಿ, ಸ್ಪಷ್ಟವಾಗಿ ನಮೂದಿಸಿ",
      QuestionId: 45,
      QuestionPaperId: 45,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Education Details",
      SubCategoryName: "Education Details",
    },
    {
      AdditionalComment: true,
      AdditionalQuestion:"If Others, specify",
      AnswerChoices: ["Kannada", 
      "Telugu",
      "Marathi",
      "Hindi",
      "Tamil",
      "Tulu",
      "Malayalam",
      "Others"],
      AnswerChoices_KN: ["ಕನ್ನಡ", 
      "ತೆಲುಗು",
      "ಮರಾಠಿ",
      "ಹಿಂದಿ",
      "ತಮಿಳು",
      "ತುಳು",
      "ಮಲಯಾಳಂ",
      "ಇತರೆ"],
      CategoryDesc: "Education Details",
      CategoryName: "Education Details",
      DisplaySequence: 46,
      Id: 46,
      QText: "Write",
      QText_KN: "ಬರವಣಿಗೆ",
      QuestionId: 46,
      QuestionPaperId: 46,
      QuestionTypeName: "Multiple Select",
      SubCategoryDesc: "Education Details",
      SubCategoryName: "Education Details",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [],
      CategoryDesc: "Education Details",
      CategoryName: "Education Details",
      DisplaySequence: 47,
      Id: 47,
      QText: "If Others, specify",
        QText_KN:"ಇತರೆಯಾದಲ್ಲಿ, ಸ್ಪಷ್ಟವಾಗಿ ನಮೂದಿಸಿಲಿ",
      QuestionId: 47,
      QuestionPaperId: 47,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Education Details",
      SubCategoryName: "Education Details",
    },
    {
      AdditionalComment: true,
      AdditionalQuestion:"If Others, specify",
      AnswerChoices: ["Kannada", 
      "Telugu",
      "Marathi",
      "Hindi",
      "Tamil",
      "Tulu",
      "Malayalam",
      "Others"],
      AnswerChoices_KN: ["ಕನ್ನಡ", 
      "ತೆಲುಗು",
      "ಮರಾಠಿ",
      "ಹಿಂದಿ",
      "ತಮಿಳು",
      "ತುಳು",
      "ಮಲಯಾಳಂ",
      "ಇತರೆ"],
      CategoryDesc: "Education Details",
      CategoryName: "Education Details",
      DisplaySequence: 48,
      Id: 48,
      QText: "Read",
      QText_KN: "ಓದುವುದು",
      QuestionId: 48,
      QuestionPaperId: 48,
      QuestionTypeName: "Multiple Select",
      SubCategoryDesc: "Education Details",
      SubCategoryName: "Education Details",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [],
      CategoryDesc: "Education Details",
      CategoryName: "Education Details",
      DisplaySequence: 49,
      Id: 49,
      QText: "If Others, specify",
        QText_KN:"ಇತರೆಯಾದಲ್ಲಿ, ಸ್ಪಷ್ಟವಾಗಿ ನಮೂದಿಸಿ",
      QuestionId: 49,
      QuestionPaperId: 49,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Education Details",
      SubCategoryName: "Education Details",
    },
    {
      AdditionalComment: false,
      AnswerChoices: ["Yes", "No"],
      AnswerChoices_KN: ["ಹೌದು", "ಇಲ್ಲ"],
      CategoryDesc: "Education Details",
      CategoryName: "Education Details",
      DisplaySequence: 50,
      Id: 50,
      QText: "Were you discriminated in school/college due to gender identity?",
      QText_KN: "ಲಿಂಗ ಗುರುತಿನ ಕಾರಣದಿಂದ ನೀವು ಶಾಲೆ/ಕಾಲೇಜುಗಳಲ್ಲಿ ತಾರತಮ್ಯಕ್ಕೆ ಒಳಗಾಗಿದ್ದೀರಾ?",
      QuestionId: 50,
      QuestionPaperId: 50,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Education Details",
      SubCategoryName: "Education Details",
    },
    {
      AdditionalComment: false,
      AnswerChoices: ["Yes", "No"],
      AnswerChoices_KN: ["ಹೌದು", "ಇಲ್ಲ"],
      CategoryDesc: "Education Details",
      CategoryName: "Education Details",
      DisplaySequence: 51,
      Id: 51,
      QText:
        "Were you pushed out of school/college/university due to Identity?",
        QText_KN: "ಗುರುತಿನ ಕಾರಣದಿಂದ ನೀವು ಶಾಲೆ/ಕಾಲೇಜು/ವಿಶ್ವವಿದ್ಯಾಲಯದಿಂದ ಹೊರಕ್ಕೆ ತಳ್ಳಲ್ಪಟ್ಟಿದ್ದೀರಾ?",
      QuestionId: 51,
      QuestionPaperId: 51,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Education Details",
      SubCategoryName: "Education Details",
    },
    {
      AdditionalComment: false,
      AnswerChoices: ["Yes", "No"],
      AnswerChoices_KN: ["ಹೌದು", "ಇಲ್ಲ"],
      CategoryDesc: "Education Details",
      CategoryName: "Education Details",
      DisplaySequence: 52,
      Id: 52,
      QText:"Were you subjected to violence due to gender identity while studying?",
      QText_KN: "ನೀವು ಅಧ್ಯಯನ ಮಾಡುವಾಗ ಲಿಂಗ ಗುರುತಿಸುವಿಕೆಯಿಂದಾಗಿ ಹಿಂಸೆಗೆ ಒಳಗಾಗಿದ್ದೀರಾ?",
      QuestionId: 52,
      QuestionPaperId: 52,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Education Details",
      SubCategoryName: "Education Details",
    },
  ],
};

export default Education;
