const Employment = {
  Id: 70,
  Name: "Employment Details",
  QuestionCount: 22,
  Questions: [
    {
      AdditionalComment: false,
      AnswerChoices: [
        { AText: "Unemployed", Id: 4543 },
        { AText: "Employed", Id: 4544 },
        { AText: "Self Employed", Id: 4545 },
        { AText: "Others", Id: 4546 },
      ],
      CategoryDesc: "EDCS",
      CategoryName: "Karmani V0.1",
      DisplaySequence: 1,
      Id: 1868,
      QText: "Employment status:",
      QuestionId: 296,
      QuestionPaperId: 70,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Emp",
      SubCategoryName: "3.Employment",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [],
      CategoryDesc: "EDCS",
      CategoryName: "Karmani V0.1",
      DisplaySequence: 2,
      Id: 1878,
      QText: "If other Employment status , specify",
      QuestionId: 297,
      QuestionPaperId: 70,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Emp",
      SubCategoryName: "3.Employment",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [
        { AText: "State Government", Id: 4547 },
        { AText: "Central Government", Id: 4548 },
        { AText: "Private", Id: 4549 },
        { AText: "Corporate", Id: 4550 },
        { AText: "Business", Id: 4551 },
        { AText: "NGO", Id: 4552 },
        { AText: "CBO", Id: 4553 },
        { AText: "Unorganized Sector", Id: 4554 },
        { AText: "Contract worker", Id: 4555 },
        { AText: "Others", Id: 4556 },
      ],
      CategoryDesc: "EDCS",
      CategoryName: "Karmani V0.1",
      DisplaySequence: 3,
      Id: 1869,
      QText: "Nature of employment: ",
      QuestionId: 298,
      QuestionPaperId: 70,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Emp",
      SubCategoryName: "3.Employment",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [],
      CategoryDesc: "EDCS",
      CategoryName: "Karmani V0.1",
      DisplaySequence: 4,
      Id: 1879,
      QText: "If other Nature of employment , specify",
      QuestionId: 299,
      QuestionPaperId: 70,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Emp",
      SubCategoryName: "3.Employment",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [],
      CategoryDesc: "EDCS",
      CategoryName: "Karmani V0.1",
      DisplaySequence: 5,
      Id: 1880,
      QText: "Where do you work ",
      QuestionId: 300,
      QuestionPaperId: 70,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Emp",
      SubCategoryName: "3.Employment",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [
        { AText: "Monthly", Id: 4557 },
        { AText: "Daily", Id: 4558 },
        { AText: "Other", Id: 4559 },
      ],
      CategoryDesc: "EDCS",
      CategoryName: "Karmani V0.1",
      DisplaySequence: 6,
      Id: 1870,
      QText: "Is your Income",
      QuestionId: 301,
      QuestionPaperId: 70,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Emp",
      SubCategoryName: "3.Employment",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [],
      CategoryDesc: "EDCS",
      CategoryName: "Karmani V0.1",
      DisplaySequence: 7,
      Id: 1881,
      QText: "If other Income , specify",
      QuestionId: 351,
      QuestionPaperId: 70,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Emp",
      SubCategoryName: "3.Employment",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [],
      CategoryDesc: "EDCS",
      CategoryName: "Karmani V0.1",
      DisplaySequence: 8,
      Id: 1882,
      QText: "What is your Primary source of Income ",
      QuestionId: 356,
      QuestionPaperId: 70,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Emp",
      SubCategoryName: "3.Employment",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [],
      CategoryDesc: "EDCS",
      CategoryName: "Karmani V0.1",
      DisplaySequence: 9,
      Id: 1883,
      QText: "What is your secondary source of work ",
      QuestionId: 360,
      QuestionPaperId: 70,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Emp",
      SubCategoryName: "3.Employment",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [],
      CategoryDesc: "EDCS",
      CategoryName: "Karmani V0.1",
      DisplaySequence: 10,
      Id: 1884,
      QText: "Your secondary source of income: ",
      QuestionId: 363,
      QuestionPaperId: 70,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Emp",
      SubCategoryName: "3.Employment",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [
        { AText: "below 1 lakh", Id: 4560 },
        { AText: "1 lakh and above", Id: 4561 },
        { AText: "below 3 lakhs", Id: 4562 },
        { AText: "3 lakhs and above", Id: 4563 },
        { AText: "5lakhs and above ", Id: 4564 },
      ],
      CategoryDesc: "EDCS",
      CategoryName: "Karmani V0.1",
      DisplaySequence: 11,
      Id: 1871,
      QText: "Your Annual Income: ",
      QuestionId: 368,
      QuestionPaperId: 70,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Emp",
      SubCategoryName: "3.Employment",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [
        { AText: "Yes", Id: 4565 },
        { AText: "No", Id: 4566 },
      ],
      CategoryDesc: "EDCS",
      CategoryName: "Karmani V0.1",
      DisplaySequence: 12,
      Id: 1872,
      QText:
        "Do you have any position of power in any organization or association ",
      QuestionId: 375,
      QuestionPaperId: 70,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Emp",
      SubCategoryName: "3.Employment",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [],
      CategoryDesc: "EDCS",
      CategoryName: "Karmani V0.1",
      DisplaySequence: 13,
      Id: 1885,
      QText: "If  any position in organization , specify",
      QuestionId: 381,
      QuestionPaperId: 70,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Emp",
      SubCategoryName: "3.Employment",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [
        { AText: "MGNREGA card", Id: 4567 },
        { AText: "Union membership", Id: 4568 },
        { AText: "Cooperative society membership", Id: 4569 },
        { AText: "Others", Id: 4570 },
      ],
      CategoryDesc: "EDCS",
      CategoryName: "Karmani V0.1",
      DisplaySequence: 14,
      Id: 1873,
      QText: "Employment  cards and memberships: ",
      QuestionId: 384,
      QuestionPaperId: 70,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Emp",
      SubCategoryName: "3.Employment",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [],
      CategoryDesc: "EDCS",
      CategoryName: "Karmani V0.1",
      DisplaySequence: 15,
      Id: 1886,
      QText: "If other employment cards ,specify",
      QuestionId: 394,
      QuestionPaperId: 70,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Emp",
      SubCategoryName: "3.Employment",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [
        { AText: "Yes", Id: 4571 },
        { AText: "No", Id: 4572 },
      ],
      CategoryDesc: "EDCS",
      CategoryName: "Karmani V0.1",
      DisplaySequence: 16,
      Id: 1874,
      QText: "Are you registered with any employment agency ",
      QuestionId: 396,
      QuestionPaperId: 70,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Emp",
      SubCategoryName: "3.Employment",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [],
      CategoryDesc: "EDCS",
      CategoryName: "Karmani V0.1",
      DisplaySequence: 17,
      Id: 1887,
      QText: "If Registered with any employment agency , specify ",
      QuestionId: 398,
      QuestionPaperId: 70,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Emp",
      SubCategoryName: "3.Employment",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [
        { AText: "Yes", Id: 4573 },
        { AText: "No", Id: 4574 },
      ],
      CategoryDesc: "EDCS",
      CategoryName: "Karmani V0.1",
      DisplaySequence: 18,
      Id: 1875,
      QText: "Do you have money saving investments ",
      QuestionId: 403,
      QuestionPaperId: 70,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Emp",
      SubCategoryName: "3.Employment",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [
        { AText: "Yes", Id: 4575 },
        { AText: "No", Id: 4576 },
      ],
      CategoryDesc: "EDCS",
      CategoryName: "Karmani V0.1",
      DisplaySequence: 19,
      Id: 1876,
      QText: "Do you have loans ",
      QuestionId: 407,
      QuestionPaperId: 70,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Emp",
      SubCategoryName: "3.Employment",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [],
      CategoryDesc: "EDCS",
      CategoryName: "Karmani V0.1",
      DisplaySequence: 20,
      Id: 1888,
      QText: "How much loan do you have ",
      QuestionId: 411,
      QuestionPaperId: 70,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Emp",
      SubCategoryName: "3.Employment",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [
        { AText: "Savings Bank account", Id: 4577 },
        { AText: "Recurring deposit account", Id: 4578 },
        { AText: "Fixed deposit account", Id: 4579 },
        { AText: "Self help group account", Id: 4580 },
        { AText: "Post office savings account", Id: 4581 },
        { AText: "Chit funds account", Id: 4582 },
        { AText: "LIC", Id: 4583 },
        { AText: "Others", Id: 4584 },
      ],
      CategoryDesc: "EDCS",
      CategoryName: "Karmani V0.1",
      DisplaySequence: 21,
      Id: 1877,
      QText: "Which of the following accounts do you have: ",
      QuestionId: 415,
      QuestionPaperId: 70,
      QuestionTypeName: "Multi Select",
      SubCategoryDesc: "Emp",
      SubCategoryName: "3.Employment",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [],
      CategoryDesc: "EDCS",
      CategoryName: "Karmani V0.1",
      DisplaySequence: 22,
      Id: 1889,
      QText: "If other Accounts , specify ",
      QuestionId: 428,
      QuestionPaperId: 70,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Emp",
      SubCategoryName: "3.Employment",
    },
  ],
};
export default Employment;
