const Employment = {
  Id: 1,
  Name: "Employment Details",
  QuestionCount: 29,
  EntityType: "Employment Details",
  Questions: [
    {
      AdditionalComment:true,
      CategoryDesc: "Employment Details",
      AdditionalQuestion:"If Others, specify",
      AnswerChoices: ["Unemployment", "Employed", "Self employed", "Others"],
      AnswerChoices_KN:["ನಿರುದ್ಯೋಗ","ಉದ್ಯೋಗದಲ್ಲಿರುವುದು","ಸ್ವಯಂ ಉದ್ಯೋಗಿ","ಇತರರು"],
      CategoryName: "Employment Details",
      DisplaySequence: 53,
      Id: 53,
      QText: "Employment status",
      QText_KN: "ಉದ್ಯೋಗ ಸ್ಥಿತಿ",
      QuestionId: 53,
      QuestionPaperId: 53,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Employment Details",
      SubCategoryName: "Employment Details",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [],
      CategoryDesc: "Employment Details",
      CategoryName: "Employment Details",
      DisplaySequence: 54,
      Id: 54,
      QText: "If Other specify",
        QText_KN:"ಇತರೆಯಾದಲ್ಲಿ, ಸ್ಪಷ್ಟವಾಗಿ ನಮೂದಿಸಿ",
      QuestionId: 54,
      QuestionPaperId: 54,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Employment Details",
      SubCategoryName: "Employment Details",
    },
    {
      AdditionalComment:true,
      AdditionalQuestion:"If Others, specify",
      CategoryDesc: "Employment Details",
      AnswerChoices: [
        "State Government",
        "Central Government",
        "Private",
        "Corporate",
        "Business",
        "NGO",
        "CBO",
        "Unorganised Sector",
        "Contract worker",
        "Others",
      ],
      AnswerChoices_KN: [
        "ರಾಜ್ಯ ಸರ್ಕಾರ",
        "ಕೇಂದ್ರ ಸರ್ಕಾರ",
        "ಖಾಸಗಿ",
        "ಕಾರ್ಪೊರೇಟ್",
        "ವ್ಯಾಪಾರ",
        "NGO",
        "CBO",
        "ಅಸಂಘಟಿತ ವಲಯ",
        "ಗುತ್ತಿಗೆ ಕೆಲಸಗಾರ",
        "ಇತರರು",
      ],
      CategoryName: "Employment Details",
      DisplaySequence: 55,
      Id: 55,
      QText: "Nature of employment",
      QText_KN: "ಉದ್ಯೋಗದ ಸ್ವರೂಪ",
      QuestionId: 55,
      QuestionPaperId: 55,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Employment Details",
      SubCategoryName: "Employment Details",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [],
      CategoryDesc: "Employment Details",
      CategoryName: "Employment Details",
      DisplaySequence: 56,
      Id: 56,
      QText: "If Other specify",
        QText_KN:"ಇತರೆಯಾದಲ್ಲಿ, ಸ್ಪಷ್ಟವಾಗಿ ನಮೂದಿಸಿ",
      QuestionId: 56,
      QuestionPaperId: 56,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Employment Details",
      SubCategoryName: "Employment Details",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [],
      CategoryDesc: "Employment Details",
      CategoryName: "Employment Details",
      DisplaySequence: 57,
      Id: 57,
      QText: "Where do you work?",
      QText_KN: "ನೀನು ಎಲ್ಲಿ ಕೆಲಸ ಮಾಡುತ್ತೀಯ?",
      QuestionId: 57,
      QuestionPaperId: 57,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Employment Details",
      SubCategoryName: "Employment Details",
    },
    {
      AdditionalComment:true,
      AdditionalQuestion:"If Others, specify",
      CategoryDesc: "Employment Details",
      AnswerChoices: ["Monthly", "Daily", "Others"],
      AnswerChoices_KN: ["ಮಾಸಿಕ", "ಪ್ರತಿದಿನ", "ಇತರರು"],
      CategoryName: "Employment Details",
      DisplaySequence: 58,
      Id: 58,
      QText: "Is your income",
      QText_KN: "ನಿಮ್ಮ ಆದಾಯವೇ",
      QuestionId: 58,
      QuestionPaperId: 58,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Employment Details",
      SubCategoryName: "Employment Details",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [],
      CategoryDesc: "Employment Details",
      CategoryName: "Employment Details",
      DisplaySequence: 59,
      Id: 59,
      QText: "If Others, specify",
        QText_KN:"ಇತರೆಯಾದಲ್ಲಿ, ಸ್ಪಷ್ಟವಾಗಿ ನಮೂದಿಸಿ್",
      QuestionId: 59,
      QuestionPaperId: 59,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Employment Details",
      SubCategoryName: "Employment Details",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [],
      CategoryDesc: "Employment Details",
      CategoryName: "Employment Details",
      DisplaySequence: 60,
      Id: 60,
      QText: "What is your Primary source of Income?",
      QText_KN: "ನಿಮ್ಮ ಆದಾಯದ ಪ್ರಾಥಮಿಕ ಮೂಲ ಯಾವುದು?",
      QuestionId: 60,
      QuestionPaperId: 60,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Employment Details",
      SubCategoryName: "Employment Details",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [],
      CategoryDesc: "Employment Details",
      CategoryName: "Employment Details",
      DisplaySequence: 61,
      Id: 61,
      QText: "What is your secondary source of work?",
      QText_KN: "ನಿಮ್ಮ ದ್ವಿತೀಯಕ ಕೆಲಸದ ಮೂಲ ಯಾವುದು?",
      QuestionId: 61,
      QuestionPaperId: 61,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Employment Details",
      SubCategoryName: "Employment Details",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [],
      CategoryDesc: "Employment Details",
      CategoryName: "Employment Details",
      DisplaySequence: 62,
      Id: 62,
      QText: "Your secondary source of income?",
      QText_KN: "ನಿಮ್ಮ ದ್ವಿತೀಯ ಆದಾಯದ ಮೂಲ?",
      QuestionId: 62,
      QuestionPaperId: 62,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Employment Details",
      SubCategoryName: "Employment Details",
    },
    {
      CategoryDesc: "Employment Details",
      AnswerChoices: [
        "Below 1 lakh",
        "1 lakh and above",
        "Below 55 lakhs",
        "55 lakhs and above",
        "57 lakhs and above",
      ],
      AnswerChoices_KN: [
        "1 ಲಕ್ಷಕ್ಕಿಂತ ಕಡಿಮೆ",
        "1 ಲಕ್ಷ ಮತ್ತು ಹೆಚ್ಚಿನದು",
        "55 ಲಕ್ಷಕ್ಕಿಂತ ಕಡಿಮೆ",
        "55 ಲಕ್ಷ ಮತ್ತು ಹೆಚ್ಚಿನದು",
        "57 ಲಕ್ಷ ಮತ್ತು ಹೆಚ್ಚಿನದು",
      ],
      CategoryName: "Employment Details",
      DisplaySequence: 63,
      Id: 63,
      QText: "Your annual income",
      QText_KN: "ನಿಮ್ಮ ವಾರ್ಷಿಕ ಆದಾಯ",
      QuestionId: 63,
      QuestionPaperId: 63,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Employment Details",
      SubCategoryName: "Employment Details",
    },
    {
      CategoryDesc: "Employment Details",
      AnswerChoices: ["Yes", "No"],
      AnswerChoices_KN: ["ಹೌದು", "ಇಲ್ಲ"],
      CategoryName: "Employment Details",
      DisplaySequence: 64,
      Id: 64,
      QText:
        "Do you have any Position or Power in any organization or association?",
        QText_KN: "ನೀವು ಯಾವುದೇ ಸಂಸ್ಥೆ ಅಥವಾ ಸಂಘದಲ್ಲಿ ಯಾವುದೇ ಸ್ಥಾನ ಅಥವಾ ಅಧಿಕಾರವನ್ನು ಹೊಂದಿದ್ದೀರಾ?",
      QuestionId: 64,
      QuestionPaperId: 64,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Employment Details",
      SubCategoryName: "Employment Details",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [],
      CategoryDesc: "Employment Details",
      CategoryName: "Employment Details",
      DisplaySequence: 65,
      Id: 65,
      QText: "If Yes, specify",
      QText_KN: "ಹೌದು ಎಂದಾದರೆ ಸೂಚಿಸಿ",
      QuestionId: 65,
      QuestionPaperId: 65,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Employment Details",
      SubCategoryName: "Employment Details",
    },
    {
      AdditionalComment:true,
      AdditionalQuestion:"If Others, specify",
      CategoryDesc: "Employment Details",
      AnswerChoices: [
        "MNREGA card",
        "Union membership",
        "Cooperative society membership",
        "Others",
      ],
      AnswerChoices_KN: [
        "MNREGA ಕಾರ್ಡ್",
        "ಒಕ್ಕೂಟದ ಸದಸ್ಯತ್ವ",
        "ಸಹಕಾರ ಸಂಘದ ಸದಸ್ಯತ್ವ",
        "ಇತರರು",
      ],
      CategoryName: "Employment Details",
      DisplaySequence: 66,
      Id: 66,
      QText: "Employment cards and memberships",
      QText_KN: "ಉದ್ಯೋಗ ಕಾರ್ಡ್‌ಗಳು ಮತ್ತು ಸದಸ್ಯತ್ವಗಳು:",
      QuestionId: 66,
      QuestionPaperId: 66,
      QuestionTypeName: "Multiple Select",
      SubCategoryDesc: "Employment Details",
      SubCategoryName: "Employment Details",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [],
      CategoryDesc: "Employment Details",
      CategoryName: "Employment Details",
      DisplaySequence: 67,
      Id: 67,
      QText: "If Others, specify",
        QText_KN:"ಇತರೆಯಾದಲ್ಲಿ, ಸ್ಪಷ್ಟವಾಗಿ ನಮೂದಿಸಿ್",
      QuestionId: 67,
      QuestionPaperId: 67,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Employment Details",
      SubCategoryName: "Employment Details",
    },
    {
      CategoryDesc: "Employment Details",
      AnswerChoices: ["Yes", "No"],
      AnswerChoices_KN: ["ಹೌದು", "ಇಲ್ಲ"],
      CategoryName: "Employment Details",
      DisplaySequence: 68,
      Id: 68,
      QText: "Are you registered with any employment agency?",
      QText_KN: "ನೀವು ಯಾವುದೇ ಉದ್ಯೋಗ ಏಜೆನ್ಸಿಯಲ್ಲಿ ನೋಂದಾಯಿಸಿಕೊಂಡಿದ್ದೀರಾ?",
      QuestionId: 68,
      QuestionPaperId: 68,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Employment Details",
      SubCategoryName: "Employment Details",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [],
      CategoryDesc: "Employment Details",
      CategoryName: "Employment Details",
      DisplaySequence: 69,
      Id: 69,
      QText: "If Yes, which",
      QText_KN: "ಹೌದಾದರೆ ಯಾವುದು",
      QuestionId: 69,
      QuestionPaperId: 69,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Employment Details",
      SubCategoryName: "Employment Details",
    },
    {
      CategoryDesc: "Employment Details",
      AnswerChoices: ["Yes", "No"],
      AnswerChoices_KN: ["ಹೌದು", "ಇಲ್ಲ"],
      CategoryName: "Employment Details",
      DisplaySequence: 70,
      Id: 70,
      QText: "Do you have money savings investments?",
      QText_KN: "ನೀವು ಹಣ ಉಳಿತಾಯ ಹೂಡಿಕೆಗಳನ್ನು ಹೊಂದಿದ್ದೀರಾ?",
      QuestionId: 70,
      QuestionPaperId: 70,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Employment Details",
      SubCategoryName: "Employment Details",
    },
    {
      CategoryDesc: "Employment Details",
      AnswerChoices: ["Yes", "No"],
      AnswerChoices_KN: ["ಹೌದು", "ಇಲ್ಲ"],
      CategoryName: "Employment Details",
      DisplaySequence: 71,
      Id: 71,
      QText: "Do you have loans?",
      QText_KN: "ನೀವು ಸಾಲ ಹೊಂದಿದ್ದೀರಾ?",
      QuestionId: 71,
      QuestionPaperId: 71,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Employment Details",
      SubCategoryName: "Employment Details",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [],
      CategoryDesc: "Employment Details",
      CategoryName: "Employment Details",
      DisplaySequence: 72,
      Id: 72,
      QText: "How much loan do you have?",
      QText_KN: "ನಿಮ್ಮ ಬಳಿ ಎಷ್ಟು ಸಾಲವಿದೆ?",
      QuestionId: 72,
      QuestionPaperId: 72,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Employment Details",
      SubCategoryName: "Employment Details",
    }
    ,
    {
      AdditionalComment:true,
      AdditionalQuestion:"If Other, specify",
      CategoryDesc: "Employment Details",
      AnswerChoices: ["Saving bank account", "Recurring deposit account", "Fixed deposit account","Self help group account","Post office savings account",
                      "Chit fund savings account","LIC","Others"],
      AnswerChoices_KN: ["ಬ್ಯಾಂಕ್ ಖಾತೆಯನ್ನು ಉಳಿಸಲಾಗುತ್ತಿದೆ", "ಮರುಕಳಿಸುವ ಠೇವಣಿ ಖಾತೆ", "ಸ್ಥಿರ ಠೇವಣಿ ಖಾತೆ","ಸ್ವಸಹಾಯ ಗುಂಪು ಖಾತೆ","ಪೋಸ್ಟ್ ಆಫೀಸ್ ಉಳಿತಾಯ ಖಾತೆ",
                      "ಚಿಟ್ ಫಂಡ್ ಉಳಿತಾಯ ಖಾತೆ","ಎಲ್.ಐ.ಸಿ","ಇತರರು"],
      CategoryName: "Employment Details",
      DisplaySequence: 73,
      Id: 73,
      QText: "Which of the following accounts do you have?",
      QText_KN: "ಈ ಕೆಳಗಿನ ಯಾವ ಖಾತೆಗಳನ್ನು ನೀವು ಹೊಂದಿರುವಿರಿ?",
      QuestionId: 73,
      QuestionPaperId: 73,
      QuestionTypeName: "Multi Select",
      SubCategoryDesc: "Employment Details",
      SubCategoryName: "Employment Details",
    }
    ,
    {
      AdditionalComment: false,
      AnswerChoices: [],
      CategoryDesc: "Employment Details",
      CategoryName: "Employment Details",
      DisplaySequence: 74,
      Id: 74,
      QText: "If Others, specify",
        QText_KN:"ಇತರೆಯಾದಲ್ಲಿ, ಸ್ಪಷ್ಟವಾಗಿ ನಮೂದಿಸಿ್",
      QuestionId: 74,
      QuestionPaperId: 74,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Employment Details",
      SubCategoryName: "Employment Details",
    },
  ],
};

export default Employment;
