const Health = {
  Id: 1,
  Name: "Health",
  QuestionCount: 140,
  EntityType: "Health",
  Questions: [
    {
      AdditionalComment:true,
      AdditionalQuestion:"If Others, specify",
      CategoryDesc: "Health",
      AnswerChoices: [
        "Government Hospital",
        "Private Hospital",
        "Charity Hospital",
        "Others",
      ],
      AnswerChoices_KN: [
        " ಸರ್ಕಾರಿ ಆಸ್ಪತ್ರೆ",
        "ಖಾಸಗಿ ಆಸ್ಪತ್ರೆ",
        "ಚಾರಿಟಿ ಆಸ್ಪತ್ರೆಗಳು",
        "ಇತರೆ",
      ],
      CategoryName: "Health",
      DisplaySequence: 112,
      Id: 112,
      QText: "Where do you go for common heath issues?",
      QText_KN: "ಸಾಮಾನ್ಯ ಹೀತ್ ಸಮಸ್ಯೆಗಳಿಗೆ ನೀವು ಎಲ್ಲಿಗೆ ಹೋಗುತ್ತೀರಿ?",
      QuestionId: 112,
      QuestionPaperId: 112,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Health",
      SubCategoryName: "Health",
    },
    {
      CategoryDesc: "Health",
      AnswerChoices: [],
      CategoryName: "Health",
      DisplaySequence: 113,
      Id: 113,
      QText: "If Others, specify",
      QText_KN: "ಇತರೆಯಾದಲ್ಲಿ, ಸ್ಪಷ್ಟವಾಗಿ ನಮೂದಿಸಿ",
      QuestionId: 113,
      QuestionPaperId: 113,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Health",
      SubCategoryName: "Health",
    },
    {
      AdditionalComment:true,
      AdditionalQuestion:"If Others, specify",
      CategoryDesc: "Health",
      AnswerChoices: [
        "Diabetes",
        "Blood Pressure",
        "Kidney issues",
        "Thyroid",
        "Liver Issues",
        "Nervous Issues",
        "Arthritis",
        "Heart Issues",
        "Lungs Issues",
        "Gynecology Issues",
        "Others",
      ],
      AnswerChoices_KN: [
        "ಮಧುಮೇಹ",
        " ರಕ್ತದೊತ್ತಡ",
        " ಕಿಡ್ನಿ ಸಮಸ್ಯೆ",
        " ಥೈರಾಯ್ಡ್",
        " ಲಿವರ್ ಸಮಸ್ಯೆ",
        " ನರಗಳ ಸಮಸ್ಯೆ",
        " ಸಂಧಿವಾತ",
        " ಹೃದಯ ಸಮಸ್ಯೆ",
        " ಶ್ವಾಸಕೋಶ ಸಮಸ್ಯೆ",
        " ಸ್ತ್ರೀ-ಸಂಬಂಧೀ ರೋಗ ಸಮಸ್ಯೆ",
        " ಇತರೆ",

      ],
      CategoryName: "Health",
      DisplaySequence: 114,
      Id: 114,
      QText: "Are you suffering from any health issues?",
      QText_KN: "ನೀವು ಯಾವುದೇ ಆರೋಗ್ಯ ಸಮಸ್ಯೆಗಳಿಂದ ಬಳಲುತ್ತಿದ್ದೀರಾ?",
      QuestionId: 114,
      QuestionPaperId: 114,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Health",
      SubCategoryName: "Health",
    },
    {
      CategoryDesc: "Health",
      AnswerChoices: [],
      CategoryName: "Health",
      DisplaySequence: 115,
      Id: 115,
      QText: "If others, specify",
      QText_KN: "ಇತರೆಯಾದಲ್ಲಿ, ಸ್ಪಷ್ಟವಾಗಿ ನಮೂದಿಸಿ",
      QuestionId: 115,
      QuestionPaperId: 115,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Health",
      SubCategoryName: "Health",
    },
    {
      CategoryDesc: "Health",
      AnswerChoices: ["Yes", "No"],
      AnswerChoices_KN: ["ಹೌದು ", "ಇಲ್ಲ"],
      CategoryName: "Health",
      DisplaySequence: 116,
      Id: 116,
      QText:
        "Do you identity yourself as trans person when you go to the hospital?",
        QText_KN: "ನೀವು ಆಸ್ಪತ್ರೆಗೆ ಹೋದಾಗ ನಿಮ್ಮನ್ನು ಟ್ರಾನ್ಸ್ ವ್ಯಕ್ತಿ ಎಂದು ಗುರುತಿಸುತ್ತೀರಾ?",
      QuestionId: 116,
      QuestionPaperId: 116,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Health",
      SubCategoryName: "Health",
    },
    {
      CategoryDesc: "Health",
      AnswerChoices: [
        "Humiliation",
        "Discrimination",
        "Untouchability",
        "Denial of treatment",
        "Harsh language",
        "No respect in taking",
        "No giving of full information of the health issues faced",
        "Silent not responding to the health issues except for giving medicine",
        "Others",
      ],
      AnswerChoices_KN: [
        "ಅವಮಾನ",
        "ತಾರತಮ್ಯ  ",
        "ಅಸ್ಪೃಶ್ಯತೆ ",
        "ಚಿಕಿತ್ಸೆಗೆ ನಿರಾಕರಣೆ",
        "ಕಟುವಾದ ಭಾಷೆ ",
        "ಮಾತಿನಲ್ಲಿ ಗೌರವ ಇಲ್ಲ ",
        "ಎದುರಿಸುತ್ತಿರುವ ಆರೋಗ್ಯ ಸಮಸ್ಯೆಗಳ ಕುರಿತು ಪೂರ್ಣ ಮಾಹಿತಿ ನೀಡುತ್ತಿಲ್ಲ ",
        "ಔಷಧಿ ನೀಡುವುದರ ಹೊರತು ಆರೋಗ್ಯ ಸಮಸ್ಯೆಗಳಿಗೆ ಸ್ಪಂದಿಸದೆ ಮೌನ",
        "ಇತರೆ ",

      ],
      CategoryName: "Health",
      DisplaySequence: 117,
      Id: 117,
      QText:
        "Did you face any of the following when you went for treatment for common health issues?",
        QText_KN: "ನೀವು ಸಾಮಾನ್ಯ ಆರೋಗ್ಯ ಸಮಸ್ಯೆಗಳಿಗೆ ಚಿಕಿತ್ಸೆಗಾಗಿ ಹೋದಾಗ ಈ ಕೆಳಗಿನ ಯಾವುದನ್ನಾದರೂ ನೀವು ಎದುರಿಸಿದ್ದೀರಾ?",
      QuestionId: 117,
      QuestionPaperId: 117,
      QuestionTypeName: "Multiple Select",
      SubCategoryDesc: "Health",
      SubCategoryName: "Health",
    },
    {
      CategoryDesc: "Health",
      AnswerChoices: ["Yes", "No"],
      AnswerChoices_KN: ["ಹೌದು ", "ಇಲ್ಲ"],
      CategoryName: "Health",
      DisplaySequence: 118,
      Id: 118,
      QText: "Have you undergone Gender Affirmation Surgery (GAS)?",
      QText_KN: "ನೀವು ಲಿಂಗ ದೃಢೀಕರಣ ಶಸ್ತ್ರಚಿಕಿತ್ಸೆಗೆ ಒಳಗಾಗಿದ್ದೀರಾ (GAS)?",
      QuestionId: 118,
      QuestionPaperId: 118,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Health",
      SubCategoryName: "Health",
    },
    {
      CategoryDesc: "Health",
      AnswerChoices: [],
      CategoryName: "Health",
      DisplaySequence: 181,
      Id: 181,
      QText: "If Yes, which surgery?",
      QText_KN: "ಹೌದು ಎಂದಾದರೆ ಎಲ್ಲಿ (ಸ್ಥಳ)?",
      QuestionId: 181,
      QuestionPaperId: 181,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Health",
      SubCategoryName: "Health",
    },
    {
      CategoryDesc: "Health",
      AnswerChoices: [],
      CategoryName: "Health",
      DisplaySequence: 119,
      Id: 119,
      QText: "If Yes, where (Place)?",
      QText_KN: "ಹೌದು ಎಂದಾದರೆ ಎಲ್ಲಿ (ಸ್ಥಳ)?",
      QuestionId: 119,
      QuestionPaperId: 119,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Health",
      SubCategoryName: "Health",
    },
    {
      CategoryDesc: "Health",
      AnswerChoices: [],
      CategoryName: "Health",
      DisplaySequence: 120,
      Id: 120,
      QText: "If Yes, Which hospital?",
      QText_KN: "ಹಾಗಿದ್ದರೆ ಯಾವ ಆಸ್ಪತ್ರೆ?",
      QuestionId: 120,
      QuestionPaperId: 120,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Health",
      SubCategoryName: "Health",
    },
    {
      CategoryDesc: "Health",
      AnswerChoices: [],
      CategoryName: "Health",
      DisplaySequence: 121,
      Id: 121,
      QText: "Cost details of GAS",
      QText_KN: "GAS ನ ವೆಚ್ಚದ ವಿವರಗಳು",
      QuestionId: 121,
      QuestionPaperId: 121,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Health",
      SubCategoryName: "Health",
    },
    {
      CategoryDesc: "Health",
      AnswerChoices: ["Yes", "No"],
      AnswerChoices_KN: ["ಹೌದು ", "ಇಲ್ಲ"],
      CategoryName: "Health",
      DisplaySequence: 122,
      Id: 122,
      QText: "Was it a successful surgery?",
      QText_KN: "ಇದು ಯಶಸ್ವಿ ಶಸ್ತ್ರಚಿಕಿತ್ಸೆಯಾಗಿತ್ತು?",
      QuestionId: 122,
      QuestionPaperId: 122,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Health",
      SubCategoryName: "Health",
    },
    {
      CategoryDesc: "Health",
      AnswerChoices: ["Yes", "No"],
      AnswerChoices_KN: ["ಹೌದು ", "ಇಲ್ಲ"],
      CategoryName: "Health",
      DisplaySequence: 123,
      Id: 123,
      QText: "Or it had to be redone",
      QText_KN: "ಅಥವಾ ಅದನ್ನು ಮತ್ತೆ ಮಾಡಬೇಕಾಗಿತ್ತು",
      QuestionId: 123,
      QuestionPaperId: 123,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Health",
      SubCategoryName: "Health",
    },
    {
      CategoryDesc: "Health",
      AnswerChoices: ["Yes", "No"],
      AnswerChoices_KN: ["ಹೌದು ", "ಇಲ್ಲ"],
      CategoryName: "Health",
      DisplaySequence: 124,
      Id: 124,
      QText: "Remaining surgery to be done any?",
      QText_KN: "ಉಳಿದಿರುವ ಶಸ್ತ್ರಚಿಕಿತ್ಸೆಯನ್ನಾದರೂ ಮಾಡಬೇಕೆ?",
      QuestionId: 124,
      QuestionPaperId: 124,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Health",
      SubCategoryName: "Health",
    },
    {
      CategoryDesc: "Health",
      AnswerChoices: [],
      CategoryName: "Health",
      DisplaySequence: 125,
      Id: 125,
      QText: "If Yes, specify",
      QText_KN: "ಹೌದು ಎಂದಾದರೆ ಸೂಚಿಸಿ",
      QuestionId: 125,
      QuestionPaperId: 125,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Health",
      SubCategoryName: "Health",
    },
    {
      CategoryDesc: "Health",
      AnswerChoices: ["Yes", "No"],
      AnswerChoices_KN: ["ಹೌದು ", "ಇಲ್ಲ"],
      CategoryName: "Health",
      DisplaySequence: 126,
      Id: 126,
      QText: "Are you receiving Hormone Replacement Therapy (HRT)?",
      QText_KN: "ನೀವು ಹಾರ್ಮೋನ್ ರಿಪ್ಲೇಸ್‌ಮೆಂಟ್ ಥೆರಪಿ (HRT) ಪಡೆಯುತ್ತಿದ್ದೀರಾ?",
      QuestionId: 126,
      QuestionPaperId: 126,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Health",
      SubCategoryName: "Health",
    },
    {
      CategoryDesc: "Health",
      AnswerChoices: [],
      CategoryName: "Health",
      DisplaySequence: 127,
      Id: 127,
      QText: "If Yes, what is the cost per month?",
      QText_KN: "ಹಾಗಿದ್ದರೆ ತಿಂಗಳಿಗೆ ಎಷ್ಟು ವೆಚ್ಚವಾಗುತ್ತದೆ?",
      QuestionId: 127,
      QuestionPaperId: 127,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Health",
      SubCategoryName: "Health",
    },
    {
      AdditionalComment:true,
      AdditionalQuestion:"If Others, specify",
      CategoryDesc: "Health",
      AnswerChoices: [
        "Diabetes",
        "Blood Pressure",
        "Heart Problem",
        "Bone weakness",
        "Thyroid",
        "Obesity",
        "Others",
      ],
      AnswerChoices_KN: [

        "ಮಧುಮೇಹ",
        "ರಕ್ತದೊತ್ತಡ",
        "ಹೃದಯ ಸಮಸ್ಯೆ",
        "ಮೂಳೆ ದುರ್ಬಲತೆ ",
        "ಥೈರಾಯ್ಡ್",
        " ಬೊಜ್ಜುತನ",
        "ಇತರೆ",

      ],
      CategoryName: "Health",
      DisplaySequence: 128,
      Id: 128,
      QText: "Side effects of HRT what are you facing?",
      QText_KN: "ನೀವು ಎದುರಿಸುತ್ತಿರುವ HRT ಯ ಅಡ್ಡಪರಿಣಾಮಗಳು?",
      QuestionId: 128,
      QuestionPaperId: 128,
      QuestionTypeName: "Multiple Select",
      SubCategoryDesc: "Health",
      SubCategoryName: "Health",
    },
    {
      CategoryDesc: "Health",
      AnswerChoices: [],
      CategoryName: "Health",
      DisplaySequence: 129,
      Id: 129,
      QText: "If Others, specify",
      QText_KN: "ಇತರೆಯಾದಲ್ಲಿ, ಸ್ಪಷ್ಟವಾಗಿ ನಮೂದಿಸಿ",
      QuestionId: 129,
      QuestionPaperId: 129,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Health",
      SubCategoryName: "Health",
    },
    {
      CategoryDesc: "Health",
      AnswerChoices: ["Yes", "No"],
      AnswerChoices_KN: ["ಹೌದು ", "ಇಲ್ಲ"],
      CategoryName: "Health",
      DisplaySequence: 130,
      Id: 130,
      QText: "Have you been subjected to Conversion Therapy?",
      QText_KN: "ನೀವು ಪರಿವರ್ತನೆ ಚಿಕಿತ್ಸೆಗೆ ಒಳಪಟ್ಟಿದ್ದೀರಾ?",
      QuestionId: 130,
      QuestionPaperId: 130,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Health",
      SubCategoryName: "Health",
    },
    {
      CategoryDesc: "Health",
      AnswerChoices: [],
      CategoryName: "Health",
      DisplaySequence: 131,
      Id: 131,
      QText: "What are your monthly medical expenses?",
      QText_KN: "ನಿಮ್ಮ ಮಾಸಿಕ ವೈದ್ಯಕೀಯ ವೆಚ್ಚಗಳು ಯಾವುವು?",
      QuestionId: 131,
      QuestionPaperId: 131,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Health",
      SubCategoryName: "Health",
    },
    {
      CategoryDesc: "Health",
      AnswerChoices: ["Yes", "No"],
      AnswerChoices_KN: ["ಹೌದು ", "ಇಲ್ಲ"],
      CategoryName: "Health",
      DisplaySequence: 132,
      Id: 132,
      QText: "Do you have any disability?",
      QText_KN: "ನೀವು ಯಾವುದೇ ಅಂಗವೈಕಲ್ಯ ಹೊಂದಿದ್ದೀರಾ?",
      QuestionId: 132,
      QuestionPaperId: 132,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Health",
      SubCategoryName: "Health",
    },
    {
      AdditionalComment:true,
      AdditionalQuestion:"If Others, specify",
      CategoryDesc: "Health",
      AnswerChoices: [
        "Physical disability",
        "Mental health disability",
        "Neuro Diversity",
        "Others",
      ],
      AnswerChoices_KN: [
        "ದೈಹಿಕ ಅಂಗವೈಕಲ್ಯ",
        "ಮಾನಸಿಕ ಆರೋಗ್ಯ ರೋಗ ನಿರ್ಣಯ",
        "ನ್ಯೂರೋ ವೈವಿಧ್ಯತೆ",
        "ಇತರೆ",
      ],
      CategoryName: "Health",
      DisplaySequence: 133,
      Id: 133,
      QText: "If Yes, what kind of disability you have?",
      QText_KN: "ಹಾಗಿದ್ದರೆ ನೀವು ಯಾವ ರೀತಿಯ ಅಂಗವೈಕಲ್ಯ ಹೊಂದಿದ್ದೀರಿ?",
      QuestionId: 133,
      QuestionPaperId: 133,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Health",
      SubCategoryName: "Health",
    },
    {
      CategoryDesc: "Health",
      AnswerChoices: [],
      CategoryName: "Health",
      DisplaySequence: 134,
      Id: 134,
      QText: "If Others, specify",
      QText_KN: "ಇತರೆಯಾದಲ್ಲಿ, ಸ್ಪಷ್ಟವಾಗಿ ನಮೂದಿಸಿ",
      QuestionId: 134,
      QuestionPaperId: 134,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Health",
      SubCategoryName: "Health",
    },
    {
      CategoryDesc: "Health",
      AnswerChoices: [],
      CategoryName: "Health",
      DisplaySequence: 135,
      Id: 135,
      QText: "What kind of physical disability do you have?",
      QText_KN: "ನೀವು ಯಾವ ರೀತಿಯ ದೈಹಿಕ ಅಸಾಮರ್ಥ್ಯವನ್ನು ಹೊಂದಿದ್ದೀರಿ?",
      QuestionId: 135,
      QuestionPaperId: 135,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Health",
      SubCategoryName: "Health",
    },
    {
      CategoryDesc: "Health",
      AnswerChoices: [],
      CategoryName: "Health",
      DisplaySequence: 136,
      Id: 136,
      QText: "What kind of mental health diagnosis do you have?",
      QText_KN: "ನೀವು ಯಾವ ರೀತಿಯ ಮಾನಸಿಕ ಆರೋಗ್ಯ ರೋಗನಿರ್ಣಯವನ್ನು ಹೊಂದಿದ್ದೀರಿ?",
      QuestionId: 136,
      QuestionPaperId: 136,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Health",
      SubCategoryName: "Health",
    },
    {
      CategoryDesc: "Health",
      AnswerChoices: ["Yes", "No"],
      AnswerChoices_KN: ["ಹೌದು ", "ಇಲ್ಲ"],
      CategoryName: "Health",
      DisplaySequence: 137,
      Id: 137,
      QText: "Do you need mental health support?",
      QText_KN: "ನಿಮಗೆ ಮಾನಸಿಕ ಆರೋಗ್ಯ ಬೆಂಬಲ ಬೇಕೇ?",
      QuestionId: 137,
      QuestionPaperId: 137,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Health",
      SubCategoryName: "Health",
    },
    {
      CategoryDesc: "Health",
      AnswerChoices: ["Yes", "No"],
      AnswerChoices_KN: ["ಹೌದು ", "ಇಲ್ಲ"],
      CategoryName: "Health",
      DisplaySequence: 138,
      Id: 138,
      QText: "Do you have access to sensitive mental health support?",
      QText_KN: "ನೀವು ಸೂಕ್ಷ್ಮ ಮಾನಸಿಕ ಆರೋಗ್ಯ ಬೆಂಬಲಕ್ಕೆ ಪ್ರವೇಶವನ್ನು ಹೊಂದಿದ್ದೀರಾ?",
      QuestionId: 138,
      QuestionPaperId: 138,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Health",
      SubCategoryName: "Health",
    },
    {
      CategoryDesc: "Health",
      AnswerChoices: [],
      CategoryName: "Health",
      DisplaySequence: 139,
      Id: 139,
      QText: "If Yes, where",
      QText_KN: "ಹೌದಾದರೆ ಎಲ್ಲಿ",
      QuestionId: 139,
      QuestionPaperId: 139,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Health",
      SubCategoryName: "Health",
    },
    {
      CategoryDesc: "Health",
      AnswerChoices: ["Yes", "No"],
      AnswerChoices_KN: ["ಹೌದು ", "ಇಲ್ಲ"],
      CategoryName: "Health",
      DisplaySequence: 140,
      Id: 140,
      QText: "Was there any medical emergency in the last one year?",
      QText_KN: "ಕಳೆದ ಒಂದು ವರ್ಷದಲ್ಲಿ ಯಾವುದಾದರೂ ವೈದ್ಯಕೀಯ ತುರ್ತು ಪರಿಸ್ಥಿತಿ ಇತ್ತು?",
      QuestionId: 140,
      QuestionPaperId: 140,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Health",
      SubCategoryName: "Health",
    },
    {
      CategoryDesc: "Health",
      AnswerChoices: ["Yes", "No"],
      AnswerChoices_KN: ["ಹೌದು ", "ಇಲ್ಲ"],
      CategoryName: "Health",
      DisplaySequence: 141,
      Id: 141,
      QText: "If Yes, were you able to afford?",
      QText_KN: "ಹೌದು ಎಂದಾದರೆ ನೀವು ಭರಿಸಲು ಸಾಧ್ಯವಾಯಿತು?",
      QuestionId: 141,
      QuestionPaperId: 141,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Health",
      SubCategoryName: "Health",
    },
    {
      CategoryDesc: "Health",
      AnswerChoices: [],
      CategoryName: "Health",
      DisplaySequence: 142,
      Id: 142,
      QText: "How much did it cost",
      QText_KN: "ಎಷ್ಟು ಖರ್ಚಾಯಿತು",
      QuestionId: 142,
      QuestionPaperId: 142,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Health",
      SubCategoryName: "Health",
    },
    {
      CategoryDesc: "Health",
      AnswerChoices: ["Yes", "No"],
      AnswerChoices_KN: ["ಹೌದು ", "ಇಲ್ಲ"],
      CategoryName: "Health",
      DisplaySequence: 143,
      Id: 143,
      QText: "Was there any monetary support for your health conditions?",
      QText_KN: "ನಿಮ್ಮ ಆರೋಗ್ಯ ಪರಿಸ್ಥಿತಿಗಳಿಗೆ ಯಾವುದೇ ಹಣಕಾಸಿನ ಬೆಂಬಲವಿದೆಯೇ?",
      QuestionId: 143,
      QuestionPaperId: 143,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Health",
      SubCategoryName: "Health",
    },
    {
      CategoryDesc: "Health",
      AnswerChoices: [],
      CategoryName: "Health",
      DisplaySequence: 144,
      Id: 144,
      QText: "If Yes, from where?",
      QText_KN: "ಹೌದು ಎಂದಾದರೆ ಎಲ್ಲಿಂದ?",
      QuestionId: 144,
      QuestionPaperId: 144,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Health",
      SubCategoryName: "Health",
    },
    {
      CategoryDesc: "Health",
      AnswerChoices: ["Yes", "No"],
      AnswerChoices_KN: ["ಹೌದು ", "ಇಲ್ಲ"],
      CategoryName: "Health",
      DisplaySequence: 145,
      Id: 145,
      QText: "Are there any dependents who need medical care?",
      QText_KN: "ವೈದ್ಯಕೀಯ ಆರೈಕೆಯ ಅಗತ್ಯವಿರುವ ಯಾವುದೇ ಅವಲಂಬಿತರು ಇದ್ದಾರೆಯೇ?",
      QuestionId: 145,
      QuestionPaperId: 145,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Health",
      SubCategoryName: "Health",
    },
    {
      CategoryDesc: "Health",
      AnswerChoices: [],
      CategoryName: "Health",
      DisplaySequence: 146,
      Id: 146,
      QText: "If Yes, how much does it cost for a month??",
      QText_KN: "ಹಾಗಿದ್ದರೆ ತಿಂಗಳಿಗೆ ಎಷ್ಟು ವೆಚ್ಚವಾಗುತ್ತದೆ??",
      QuestionId: 146,
      QuestionPaperId: 146,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Health",
      SubCategoryName: "Health",
    },
    {
      CategoryDesc: "Health",
      AnswerChoices: [],
      CategoryName: "Health",
      DisplaySequence: 134,
      Id: 134,
      QText: "Do you need any other medical support?",
      QText_KN: "ನಿಮಗೆ ಬೇರೆ ಯಾವುದಾದರೂ ವೈದ್ಯಕೀಯ ಬೆಂಬಲ ಬೇಕೇ?",
      QuestionId: 134,
      QuestionPaperId: 134,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Health",
      SubCategoryName: "Health",
    },

  ],
};

export default Health;
