const Housing = {
  Id: 1,
  Name: "Housing",
  QuestionCount: 29,
  EntityType: "Housing",
  Questions: [
    {
      AdditionalComment:true,
      AdditionalQuestion:"If Others, specify",
      CategoryDesc: "Housing",
      AnswerChoices: ["Hamam", "Hijara community home", "Others"],
      AnswerChoices_KN: ["ಹಮಾಮ್", "ಹಿಜಾರಾ ಸಮುದಾಯದ ಮನೆ", "ಇತರರು"],
      CategoryName: "Housing",
      DisplaySequence: 81,
      Id: 81,
      QText: "Do you live in community home?",
      QText_KN:"ನೀವು ಸಮುದಾಯ ಮನೆಯಲ್ಲಿ ವಾಸಿಸುತ್ತಿದ್ದೀರಾ?",
      QuestionId: 81,
      QuestionPaperId: 81,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Housing",
      SubCategoryName: "Housing",
    },

    {
      CategoryDesc: "Housing",
      AnswerChoices: [],
      CategoryName: "Housing",
      DisplaySequence: 82,
      Id: 82,
      QText: "If Others, specify ",
        QText_KN:"ಇತರೆಯಾದಲ್ಲಿ, ಸ್ಪಷ್ಟವಾಗಿ ನಮೂದಿಸಿ್",
      QuestionId: 82,
      QuestionPaperId: 82,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Housing",
      SubCategoryName: "Housing",
    },
    {
      AdditionalComment:true,
      AdditionalQuestion:"If Others, specify",
      CategoryDesc: "Housing",
      AnswerChoices: [
        "Kaccha house",
        "Semi Pucca house",
        "Pacca house",
        "Others",
      ],
      AnswerChoices_KN: [
        "ಕಚ್ಚೆ ಮನೆ",
        "ಅರೆ ಪಕ್ಕಾ ಮನೆ",
        "ಪಕ್ಕಾ ಮನೆ",
        "ಇತರರು",
      ],
      CategoryName: "Housing",
      DisplaySequence: 75,
      Id: 75,
      QText: "Type of house ",
      QText_KN:"ಮನೆಯ ಪ್ರಕಾರ",
      QuestionId: 75,
      QuestionPaperId: 75,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Housing",
      SubCategoryName: "Housing",
    },

    {
      CategoryDesc: "Housing",
      AnswerChoices: [],
      CategoryName: "Housing",
      DisplaySequence: 76,
      Id: 76,
      QText: "If Others, specify ",
        QText_KN:"ಇತರೆಯಾದಲ್ಲಿ, ಸ್ಪಷ್ಟವಾಗಿ ನಮೂದಿಸಿ್",
      QuestionId: 76,
      QuestionPaperId: 76,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Housing",
      SubCategoryName: "Housing",
    },

    {
      AdditionalComment:true,
      AdditionalQuestion:"If Others, specify",
      CategoryDesc: "Housing",
      AnswerChoices: [
        "Tin roof",
        "Thatched roof",
        "Asbestos roof",
        "Tiles roof",
        "Cement roof",
        "Others",
      ],
      AnswerChoices_KN: [
        "ತವರ ಛಾವಸಿಮೆಂಟ್ ಛಾವಣಿಣಿ",
        "ಹುಲ್ಲಿನ ಛಾವಣಿ",
        "ಕಲ್ನಾರಿನ ಛಾವಣಿ",
        "ಟೈಲ್ಸ್ ಛಾವಣಿ",
        "ಸಿಮೆಂಟ್ ಛಾವಣಿ",
        "ಇತರರು",
      ],
      CategoryName: "Housing",
      DisplaySequence: 77,
      Id: 77,
      QText: "Type of roof ",
      QText_KN:"ಛಾವಣಿಯ ವಿಧ",
      QuestionId: 77,
      QuestionPaperId: 77,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Housing",
      SubCategoryName: "Housing",
    },

    {
      CategoryDesc: "Housing",
      AnswerChoices: [],
      CategoryName: "Housing",
      DisplaySequence: 78,
      Id: 78,
      QText: "If Others, specify ",
        QText_KN:"ಇತರೆಯಾದಲ್ಲಿ, ಸ್ಪಷ್ಟವಾಗಿ ನಮೂದಿಸಿಲಿ",
      QuestionId: 78,
      QuestionPaperId: 78,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Housing",
      SubCategoryName: "Housing",
    },

    {
      AdditionalComment:true,
      AdditionalQuestion:"If Others, specify",
      CategoryDesc: "Housing",
      AnswerChoices: [
        "Own house",
        "Rented house",
        "Leased house",
        "PG",
        "Community House",
        "Friends house",
        "With parents",
        "No house on street",
        "Others",
      ],
      AnswerChoices_KN: [
        "ಸ್ವಂತ ಮನೆ",
        "ಬಾಡಿಗೆ ಮನೆ",
        "ಬಾಡಿಗೆ ಮನೆ",
        "ಪಿಜಿ",
        "ಸಮುದಾಯ ಮನೆ",
        "ಸ್ನೇಹಿತರ ಮನೆ",
        "ಪೋಷಕರೊಂದಿಗೆ",
        "ಬೀದಿಯಲ್ಲಿ ಮನೆ ಇಲ್ಲ",
        "ಇತರರು",
      ],
      CategoryName: "Housing",
      DisplaySequence: 79,
      Id: 79,
      QText: "Housing ownership ",
      QText_KN:"ವಸತಿ ಮಾಲೀಕತ್ವ",
      QuestionId: 79,
      QuestionPaperId: 79,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Housing",
      SubCategoryName: "Housing",
    },

    {
      CategoryDesc: "Housing",
      AnswerChoices: [],
      CategoryName: "Housing",
      DisplaySequence: 80,
      Id: 80,
      QText: "If Others, specify ",
        QText_KN:"ಇತರೆಯಾದಲ್ಲಿ, ಸ್ಪಷ್ಟವಾಗಿ ನಮೂದಿಸಿಲಿ",
      QuestionId: 80,
      QuestionPaperId: 80,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Housing",
      SubCategoryName: "Housing",
    },
    {
      AdditionalComment:true,
      AdditionalQuestion:"If Others, specify",
      CategoryDesc: "Housing",
      AnswerChoices: [
        "Toilet inside house",
        "Toilet outside house",
        "Shared Toilet",
        "Public Toilet",
        "Others",
      ],
      AnswerChoices_KN: [
        "ಮನೆಯೊಳಗೆ ಶೌಚಾಲಯ",
        "ಮನೆಯ ಹೊರಗೆ ಶೌಚಾಲಯ",
        "ಹಂಚಿದ ಶೌಚಾಲಯ",
        "ಸಾರ್ವಜನಿಕ ಶೌಚಾಲಯ",
        "ಇತರರು",
      ],
      CategoryName: "Housing",
      DisplaySequence: 83,
      Id: 83,
      QText: "Toilet ",
      QText_KN:"ಶೌಚಾಲಯ",
      QuestionId: 83,
      QuestionPaperId: 83,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Housing",
      SubCategoryName: "Housing",
    },

    {
      CategoryDesc: "Housing",
      AnswerChoices: [],
      CategoryName: "Housing",
      DisplaySequence: 84,
      Id: 84,
      QText: "If Others, specify ",
        QText_KN:"ಇತರೆಯಾದಲ್ಲಿ, ಸ್ಪಷ್ಟವಾಗಿ ನಮೂದಿಸಿಲಿ",
      QuestionId: 84,
      QuestionPaperId: 84,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Housing",
      SubCategoryName: "Housing",
    },

    {
      CategoryDesc: "Housing",
      AnswerChoices: ["Yes", "No"],
      AnswerChoices_KN: ["ಹೌದು", "ಇಲ್ಲ"],
      CategoryName: "Housing",
      DisplaySequence: 85,
      Id: 85,
      QText: "Do you own site? ",
      QText_KN:"ನೀವು ಸೈಟ್ ಹೊಂದಿದ್ದೀರಾ?",
      QuestionId: 85,
      QuestionPaperId: 85,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Housing",
      SubCategoryName: "Housing",
    },

    {
      AdditionalComment:true,
      AdditionalQuestion:"If Others, specify",
      CategoryDesc: "Housing",
      AnswerChoices: [
        "Corporation limited electricity",
        "Solar",
        "Wind",
        "No electricity",
        "Others",
      ],
      AnswerChoices_KN: [
        "ಕಾರ್ಪೊರೇಷನ್ ಸೀಮಿತ ವಿದ್ಯುತ್",
        "ಸೌರ",
        "ಗಾಳಿ",
        "ವಿದ್ಯುತ್ ಇಲ್ಲ",
        "ಇತರರು",
      ],
      CategoryName: "Housing",
      DisplaySequence: 86,
      Id: 86,
      QText: "Electricity ",
      QText_KN:"ವಿದ್ಯುತ್",
      QuestionId: 86,
      QuestionPaperId: 86,
      QuestionTypeName:"Multiple Select",
      SubCategoryDesc: "Housing",
      SubCategoryName: "Housing",
    },

    {
      CategoryDesc: "Housing",
      AnswerChoices: [],
      CategoryName: "Housing",
      DisplaySequence: 87,
      Id: 87,
      QText: "If Others, specify ",
        QText_KN:"ಇತರೆಯಾದಲ್ಲಿ, ಸ್ಪಷ್ಟವಾಗಿ ನಮೂದಿಸಿಲಿ",
      QuestionId: 87,
      QuestionPaperId: 87,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Housing",
      SubCategoryName: "Housing",
    },

    {
      AdditionalComment:true,
      AdditionalQuestion:"If Others, specify",
      CategoryDesc: "Housing",
      AnswerChoices: [
        "BWSSB",
        "Borewell",
        "Tank water",
        "Public well",
        "Public pump",
        "Lake",
        "Others",
      ],
      AnswerChoices_KN: [
        "BWSSB",
        "ಬೋರ್ವೆಲ್",
        "ಟ್ಯಾಂಕ್ ನೀರು",
        "ಸಾರ್ವಜನಿಕ ಬಾವಿ",
        "ಸಾರ್ವಜನಿಕ ಪಂಪ್",
        "ಸರೋವರ",
        "ಇತರರು",
      ],
      CategoryName: "Housing",
      DisplaySequence: 88,
      Id: 88,
      QText: "Water facility in house ",
      QText_KN:"ಮನೆಯಲ್ಲಿ ನೀರಿನ ಸೌಲಭ್ಯ",
      QuestionId: 88,
      QuestionPaperId: 88,
      QuestionTypeName: "Multiple Select",
      SubCategoryDesc: "Housing",
      SubCategoryName: "Housing",
    },

    {
      CategoryDesc: "Housing",
      AnswerChoices: [],
      CategoryName: "Housing",
      DisplaySequence: 89,
      Id: 89,
      QText: "If Others, specify ",
        QText_KN:"ಇತರೆಯಾದಲ್ಲಿ, ಸ್ಪಷ್ಟವಾಗಿ ನಮೂದಿಸಿಲಿ",
      QuestionId: 89,
      QuestionPaperId: 89,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Housing",
      SubCategoryName: "Housing",
    },

    {
      CategoryDesc: "Housing",
      AnswerChoices: ["Yes", "No"],
      AnswerChoices_KN: ["ಹೌದು", "ಇಲ್ಲ"],
      CategoryName: "Housing",
      DisplaySequence: 90,
      Id: 90,
      QText: "Do you have own land? ",
      QText_KN:"ನಿಮ್ಮ ಸ್ವಂತ ಭೂಮಿ ಇದೆಯೇ?",
      QuestionId: 90,
      QuestionPaperId: 90,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Housing",
      SubCategoryName: "Housing",
    },

    {
      CategoryDesc: "Housing",
      AnswerChoices: ["Commercial", "Agriculture", "Others"],
      AnswerChoices_KN: ["ವಾಣಿಜ್ಯಿಕ", "ಕೃಷಿ", "ಇತರರು"],
      CategoryName: "Housing",
      DisplaySequence: 91,
      Id: 91,
      QText: "If Yes, what type of land you have?",
      QText_KN:"ಹಾಗಿದ್ದರೆ ನಿಮ್ಮ ಬಳಿ ಯಾವ ರೀತಿಯ ಭೂಮಿ ಇದೆ?",
      QuestionId: 91,
      QuestionPaperId: 91,
      QuestionTypeName: "Multiple Select",
      SubCategoryDesc: "Housing",
      SubCategoryName: "Housing",
    },
    {
      CategoryDesc: "Housing",
      AnswerChoices: [
        "Dry land",
        "Irrigated land",
        "Wet land",
        "Agriculture land",
        "Others",
      ],
      AnswerChoices_KN: [
        "ಒಣ ಭೂಮಿ",
        "ನೀರಾವರಿ ಭೂಮಿ",
        "ಆರ್ದ್ರ ಭೂಮಿ",
        "ಕೃಷಿ ಭೂಮಿ",
        "ಇತರರು",
      ],
      CategoryName: "Housing",
      DisplaySequence: 92,
      Id: 92,
      QText: "If agriculture what is type of agriculture land?",
      QText_KN:"ಕೃಷಿಯಾದರೆ ಯಾವ ರೀತಿಯ ಕೃಷಿ ಭೂಮಿ?",
      QuestionId: 92,
      QuestionPaperId: 92,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Housing",
      SubCategoryName: "Housing",
    },

    {
      CategoryDesc: "Housing",
      AnswerChoices: [],
      CategoryName: "Housing",
      DisplaySequence: 93,
      Id: 93,
      QText: "Where ",
      QText_KN:"ಎಲ್ಲಿ",
      QuestionId: 93,
      QuestionPaperId: 93,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Housing",
      SubCategoryName: "Housing",
    },

    {
      CategoryDesc: "Housing",
      AnswerChoices: [],
      CategoryName: "Housing",
      DisplaySequence: 94,
      Id: 94,
      QText: "How much if agricultural(Acres/Guntas/Cents)?",
      QText_KN:"ಕೃಷಿಯಾಗಿದ್ದರೆ (ಎಕರೆ/ಗುಂಟಾ/ಸೆಂಟ್ಸ್) ಎಷ್ಟು?",
      QuestionId: 94,
      QuestionPaperId: 94,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Housing",
      SubCategoryName: "Housing",
    },

    {
      CategoryDesc: "Housing",
      AnswerChoices: [],
      CategoryName: "Housing",
      DisplaySequence: 95,
      Id: 95,
      QText: "If commercial(Sq.Ft)?",
      QText_KN:"ವಾಣಿಜ್ಯವಾಗಿದ್ದರೆ (ಚ.ಅಡಿ)?",
      QuestionId: 95,
      QuestionPaperId: 95,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Housing",
      SubCategoryName: "Housing",
    },

    {
      CategoryDesc: "Housing",
      AnswerChoices: ["Yes", "No"],
      AnswerChoices_KN: ["ಹೌದು", "ಇಲ್ಲ"],
      CategoryName: "Housing",
      DisplaySequence: 96,
      Id: 96,
      QText: "Do you own livestock?",
      QText_KN:"ನೀವು ಜಾನುವಾರುಗಳನ್ನು ಹೊಂದಿದ್ದೀರಾ?",
      QuestionId: 96,
      QuestionPaperId: 96,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Housing",
      SubCategoryName: "Housing",
    },

    {
      CategoryDesc: "Housing",
      AnswerChoices: [],
      CategoryName: "Housing",
      DisplaySequence: 97,
      Id: 97,
      QText: "Type of livestock ",
      QText_KN:"ಜಾನುವಾರುಗಳ ವಿಧ",
      QuestionId: 97,
      QuestionPaperId: 97,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Housing",
      SubCategoryName: "Housing",
    },

    {
      AdditionalComment:true,
      AdditionalQuestion:"If Others, specify",
      CategoryDesc: "Housing",
      AnswerChoices: [
        "Slum",
        "Housing colony",
        "Suburban area",
        "Urban area",
        "Village",
        "Town",
        "City",
        "Others",
      ],
      AnswerChoices_KN: [
        "ಕೊಳೆಗೇರಿ",
        "ವಸತಿ ಕಾಲೋನಿ",
        "ಉಪನಗರ ಪ್ರದೇಶ",
        "ನಗರ ಪ್ರದೇಶ",
        "ಗ್ರಾಮ",
        "ಪಟ್ಟಣ",
        "ನಗರ",
        "ಇತರರು",
      ],
      CategoryName: "Housing",
      DisplaySequence: 98,
      Id: 98,
      QText: "Area of residence ",
      QText_KN:"ನಿವಾಸದ ಪ್ರದೇಶ",
      QuestionId: 98,
      QuestionPaperId: 98,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Housing",
      SubCategoryName: "Housing",
    },

    {
      CategoryDesc: "Housing",
      AnswerChoices: [],
      CategoryName: "Housing",
      DisplaySequence: 99,
      Id: 99,
      QText: "If Others, specify ",
        QText_KN:"ಇತರೆಯಾದಲ್ಲಿ, ಸ್ಪಷ್ಟವಾಗಿ ನಮೂದಿಸಿಲಿ",
      QuestionId: 99,
      QuestionPaperId: 99,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Housing",
      SubCategoryName: "Housing",
    },

    {
      CategoryDesc: "Housing",
      AnswerChoices: ["Yes", "No"],
      AnswerChoices_KN: ["ಹೌದು", "ಇಲ್ಲ"],
      CategoryName: "Housing",
      DisplaySequence: 100,
      Id: 100,
      QText: " Do you own any property from your parents?",
      QText_KN:"ನಿಮ್ಮ ಪೋಷಕರಿಂದ ನೀವು ಯಾವುದೇ ಆಸ್ತಿಯನ್ನು ಹೊಂದಿದ್ದೀರಾ?",
      QuestionId: 100,
      QuestionPaperId: 100,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Housing",
      SubCategoryName: "Housing",
    },

    {
      CategoryDesc: "Housing",
      AnswerChoices: ["Yes", "No"],
      AnswerChoices_KN: ["ಹೌದು", "ಇಲ್ಲ"],
      CategoryName: "Housing",
      DisplaySequence: 101,
      Id: 101,
      QText: "Are you allowed to inherit property in your chosen gender?",
      QText_KN:"ನೀವು ಆಯ್ಕೆ ಮಾಡಿದ ಲಿಂಗದಲ್ಲಿ ಆಸ್ತಿಯನ್ನು ಆನುವಂಶಿಕವಾಗಿ ಪಡೆಯಲು ನಿಮಗೆ ಅನುಮತಿಸಲಾಗಿದೆಯೇ?",
      QuestionId: 101,
      QuestionPaperId: 101,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Housing",
      SubCategoryName: "Housing",
    },

    {
      CategoryDesc: "Housing",
      AnswerChoices: ["Yes", "No"],
      AnswerChoices_KN: ["ಹೌದು", "ಇಲ್ಲ"],
      CategoryName: "Housing",
      DisplaySequence: 102,
      Id: 102,
      QText: "Have you filed any case to get your share of property?",
      QText_KN:"ನಿಮ್ಮ ಆಸ್ತಿಯ ಪಾಲು ಪಡೆಯಲು ನೀವು ಯಾವುದೇ ಪ್ರಕರಣವನ್ನು ದಾಖಲಿಸಿದ್ದೀರಾ?",
      QuestionId: 102,
      QuestionPaperId: 102,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Housing",
      SubCategoryName: "Housing",
    },

    {
      AdditionalComment:true,
      AdditionalQuestion:"If Others, specify",
      CategoryDesc: "Housing",
      AnswerChoices: [
        "Government shelter",
        "Private shelter",
        "Transgender shelter homes",
        "Shelter home for female assigned transgender",
        "Shelter home for male assigned transgender",
        "Others",
      ],
      AnswerChoices_KN: [
        "ಸರ್ಕಾರಿ ಆಶ್ರಯ",
        "ಖಾಸಗಿ ಆಶ್ರಯ",
        "ಟ್ರಾನ್ಸ್ಜೆಂಡರ್ ಆಶ್ರಯ ಮನೆಗಳು",
        "ಮಹಿಳಾ ನಿಯೋಜಿತ ಲಿಂಗಾಯತರಿಗೆ ಆಶ್ರಯ ಮನೆ",
        "ಪುರುಷ ನಿಯೋಜಿತ ಟ್ರಾನ್ಸ್ಜೆಂಡರ್ಗಾಗಿ ಆಶ್ರಯ ಮನೆ",
        "ಇತರರು",
      ],
      CategoryName: "Housing",
      DisplaySequence: 103,
      Id: 103,
      QText: "What kind of shelter space do you require?",
      QText_KN:"ನಿಮಗೆ ಯಾವ ರೀತಿಯ ಆಶ್ರಯ ಸ್ಥಳ ಬೇಕು?",
      QuestionId: 103,
      QuestionPaperId: 103,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Housing",
      SubCategoryName: "Housing",
    },

    {
      CategoryDesc: "Housing",
      AnswerChoices: [],
      CategoryName: "Housing",
      DisplaySequence: 104,
      Id: 104,
      QText: "If Others, specify ",
        QText_KN:"ಇತರೆಯಾದಲ್ಲಿ, ಸ್ಪಷ್ಟವಾಗಿ ನಮೂದಿಸಿಲಿ",
      QuestionId: 104,
      QuestionPaperId: 104,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Housing",
      SubCategoryName: "Housing",
    },
    {
      CategoryDesc: "Housing",
      AnswerChoices: ["Yes", "No"],
      AnswerChoices_KN: ["ಹೌದು", "ಇಲ್ಲ"],
      CategoryName: "Housing",
      DisplaySequence: 105,
      Id: 105,
      QText: "Do you have the knowledge about housing schemes?",
      QText_KN:"ವಸತಿ ಯೋಜನೆಗಳ ಬಗ್ಗೆ ನಿಮಗೆ ಜ್ಞಾನವಿದೆಯೇ?",
      QuestionId: 105,
      QuestionPaperId: 105,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Housing",
      SubCategoryName: "Housing",
    },

    {
      CategoryDesc: "Housing",
      AnswerChoices: ["Yes", "No"],
      AnswerChoices_KN: ["ಹೌದು", "ಇಲ್ಲ"],
      CategoryName: "Housing",
      DisplaySequence: 106,
      Id: 106,
      QText: "Are you Beneficiary of any housing schemes?",
      QText_KN:"ನೀವು ಯಾವುದೇ ವಸತಿ ಯೋಜನೆಗಳ ಫಲಾನುಭವಿಯೇ?",
      QuestionId: 106,
      QuestionPaperId: 106,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Housing",
      SubCategoryName: "Housing",
    },

    {
      AdditionalComment:true,
      AdditionalQuestion:"If Others, specify",
      CategoryDesc: "Housing",
      AnswerChoices: [
        "Pradhanamantri Awaas Yojana urban",
        "Dr Br Ambedkar Awaas Yojana urban",
        "Vajpayee Housing scheme",
        "Devraj Urs Housing scheme",
        "Basava Housing scheme",
        "Devraj Urs Housing scheme urban",
        "Dr Br Ambedkar Niwaas Yojana Rural",
        "Pradhanamantri Awaas Yojana Rural",
        "Others",
      ],
      AnswerChoices_KN: [
        "ಪ್ರಧಾನಮಂತ್ರಿ ಆವಾಸ್ ಯೋಜನೆ ನಗರ",
        "ಡಾ ಬ್ರ ಅಂಬೇಡ್ಕರ್ ಆವಾಸ್ ಯೋಜನೆ ನಗರ",
        "ವಾಜಪೇಯಿ ವಸತಿ ಯೋಜನೆ",
        "ದೇವರಾಜ್ ಅರಸು ವಸತಿ ಯೋಜನೆ",
        "ಬಸವ ವಸತಿ ಯೋಜನೆ",
        "ದೇವರಾಜ್ ಅರಸ್ ವಸತಿ ಯೋಜನೆ ನಗರ",
        "ದೊಡ್ಡ ಅಂಬೇಡ್ಕರ್ ನಿವಾಸ ಯೋಜನೆ ಗ್ರಾಮೀಣ",
        "ಪ್ರಧಾನ ಮಂತ್ರಿ ಆವಾಸ್ ಯೋಜನೆ ಗ್ರಾಮೀಣ",
        "ಇತರರು",
      ],
      CategoryName: "Housing",
      DisplaySequence: 107,
      Id: 107,
      QText:"If Yes, under which housing scheme?",
      QText_KN:"ಹೌದಾದರೆ ಯಾವ ವಸತಿ ಯೋಜನೆಯಡಿ?",
      QuestionId: 107,
      QuestionPaperId: 107,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Housing",
      SubCategoryName: "Housing",
    },

    {
      CategoryDesc: "Housing",
      AnswerChoices: [],
      CategoryName: "Housing",
      DisplaySequence: 108,
      Id: 108,
      QText:"If others, specify ",
        QText_KN:"ಇತರೆಯಾದಲ್ಲಿ, ಸ್ಪಷ್ಟವಾಗಿ ನಮೂದಿಸಿಲಿ",
      QuestionId: 108,
      QuestionPaperId: 108,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Housing",
      SubCategoryName: "Housing",
    },

    {
      CategoryDesc: "Housing",
      AnswerChoices: ["Yes", "No"],
      AnswerChoices_KN: ["ಹೌದು", "ಇಲ್ಲ"],
      CategoryName: "Housing",
      DisplaySequence: 109,
      Id: 109,
      QText:"Do transgender need old age homes?",
      QText_KN:"ತೃತೀಯಲಿಂಗಿಗಳಿಗೆ ವೃದ್ಧಾಶ್ರಮ ಬೇಕೇ?",
      QuestionId: 109,
      QuestionPaperId: 109,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Housing",
      SubCategoryName: "Housing",
    },

    {
      AdditionalComment:true,
      AdditionalQuestion:"If Others, specify",
      CategoryDesc: "Housing",
      AnswerChoices: [
        "Radio",
        "Tv",
        "Fridge",
        "Gas connection private",
        "Gas connection govt",
        "Two wheeler",
        "Four wheeler",
        "Mobile",
        "Others",
      ],
      AnswerChoices_KN: [
        "ರೇಡಿಯೋ",
        "ಟಿವಿ",
        "ಫ್ರಿಜ್",
        "ಖಾಸಗಿ ಅನಿಲ ಸಂಪರ್ಕ",
        "ಗ್ಯಾಸ್ ಸಂಪರ್ಕ ಸರ್ಕಾರ",
        "ದ್ವಿಚಕ್ರ ವಾಹನ",
        "ನಾಲ್ಕು ಚಕ್ರದ ವಾಹನ",
        "ಮೊಬೈಲ್",
        "ಇತರರು",
      ],
      CategoryName: "Housing",
      DisplaySequence: 110,
      Id: 110,
      QText:"Tick the following assets you have",
      QText_KN:"ನೀವು ಹೊಂದಿರುವ ಕೆಳಗಿನ ಸ್ವತ್ತುಗಳನ್ನು ಟಿಕ್ ಮಾಡಿ", 
      QuestionId: 110,
      QuestionPaperId: 110,
      QuestionTypeName: "Multiple Select",
      SubCategoryDesc: "Housing",
      SubCategoryName: "Housing",
    },

    {
      CategoryDesc: "Housing",
      AnswerChoices: [],
      CategoryName: "Housing",
      DisplaySequence: 111,
      Id: 111,
      QText:"If Others, specify ",
      QText_KN:"ಇತರೆಯಾದಲ್ಲಿ, ಸ್ಪಷ್ಟವಾಗಿ ನಮೂದಿಸಿಲಿ",
      QuestionId: 111,
      QuestionPaperId: 111,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Housing",
      SubCategoryName: "Housing",
    },
  ],
};

export default Housing;
