const SocialSecurity = {
  Id: 79,
  Name: "Social Security",
  QuestionCount: 23,
  Questions: [
    {
      AdditionalComment: false,
      AnswerChoices: [
        { AText: "Yes", Id: 5338 },
        { AText: "No", Id: 5339 },
      ],
      CategoryDesc: "EDCS",
      CategoryName: "Karmani V0.1",
      DisplaySequence: 1,
      Id: 2173,
      QText: "Do you get Pension",
      QuestionId: 358,
      QuestionPaperId: 79,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "SS",
      SubCategoryName: "6.Social Security",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [
        { AText: "Indira Gandhi National Old Pension Scheme", Id: 5340 },
        { AText: "Mytri", Id: 5341 },
        { AText: "Disability Pension ", Id: 5342 },
        { AText: "Sandhya Suraksha", Id: 5343 },
        { AText: "Others", Id: 5344 },
      ],
      CategoryDesc: "EDCS",
      CategoryName: "Karmani V0.1",
      DisplaySequence: 2,
      Id: 2174,
      QText: "If yes, from which Pension scheme ",
      QuestionId: 391,
      QuestionPaperId: 79,
      QuestionTypeName: "Multi Select",
      SubCategoryDesc: "SS",
      SubCategoryName: "6.Social Security",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [],
      CategoryDesc: "EDCS",
      CategoryName: "Karmani V0.1",
      DisplaySequence: 3,
      Id: 2189,
      QText: "If Other Pension Scheme, Specify",
      QuestionId: 468,
      QuestionPaperId: 79,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "SS",
      SubCategoryName: "6.Social Security",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [
        { AText: "Yes", Id: 5345 },
        { AText: "No", Id: 5346 },
      ],
      CategoryDesc: "EDCS",
      CategoryName: "Karmani V0.1",
      DisplaySequence: 4,
      Id: 2175,
      QText: "Do you get Ration",
      QuestionId: 479,
      QuestionPaperId: 79,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "SS",
      SubCategoryName: "6.Social Security",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [
        { AText: "Antyodaya(AAY)", Id: 5347 },
        { AText: "PHH(BPL)", Id: 5348 },
        { AText: "NPHH(APL)", Id: 5349 },
        { AText: "Others", Id: 5350 },
      ],
      CategoryDesc: "EDCS",
      CategoryName: "Karmani V0.1",
      DisplaySequence: 5,
      Id: 2176,
      QText: "If yes, from which Ration scheme ",
      QuestionId: 491,
      QuestionPaperId: 79,
      QuestionTypeName: "Multi Select",
      SubCategoryDesc: "SS",
      SubCategoryName: "6.Social Security",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [],
      CategoryDesc: "EDCS",
      CategoryName: "Karmani V0.1",
      DisplaySequence: 6,
      Id: 2190,
      QText: "If Other Ration scheme, Specify",
      QuestionId: 501,
      QuestionPaperId: 79,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "SS",
      SubCategoryName: "6.Social Security",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [
        { AText: "Yes", Id: 5351 },
        { AText: "No", Id: 5352 },
      ],
      CategoryDesc: "EDCS",
      CategoryName: "Karmani V0.1",
      DisplaySequence: 7,
      Id: 2177,
      QText: "Have you received any support for business/employment",
      QuestionId: 504,
      QuestionPaperId: 79,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "SS",
      SubCategoryName: "6.Social Security",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [],
      CategoryDesc: "EDCS",
      CategoryName: "Karmani V0.1",
      DisplaySequence: 8,
      Id: 2191,
      QText: "If yes, which Business Employment Scheme",
      QuestionId: 510,
      QuestionPaperId: 79,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "SS",
      SubCategoryName: "6.Social Security",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [
        { AText: "Yes", Id: 5353 },
        { AText: "No", Id: 5354 },
      ],
      CategoryDesc: "EDCS",
      CategoryName: "Karmani V0.1",
      DisplaySequence: 9,
      Id: 2178,
      QText: "Have you received any support for education",
      QuestionId: 513,
      QuestionPaperId: 79,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "SS",
      SubCategoryName: "6.Social Security",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [],
      CategoryDesc: "EDCS",
      CategoryName: "Karmani V0.1",
      DisplaySequence: 10,
      Id: 2192,
      QText: "If yes which educational scheme/scholarship",
      QuestionId: 520,
      QuestionPaperId: 79,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "SS",
      SubCategoryName: "6.Social Security",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [
        { AText: "Yes", Id: 5355 },
        { AText: "No", Id: 5356 },
      ],
      CategoryDesc: "EDCS",
      CategoryName: "Karmani V0.1",
      DisplaySequence: 11,
      Id: 2179,
      QText: "Do you have any Caste certificate",
      QuestionId: 523,
      QuestionPaperId: 79,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "SS",
      SubCategoryName: "6.Social Security",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [
        { AText: "Yes", Id: 5357 },
        { AText: "No", Id: 5358 },
      ],
      CategoryDesc: "EDCS",
      CategoryName: "Karmani V0.1",
      DisplaySequence: 12,
      Id: 2180,
      QText: "Do you have income certificate",
      QuestionId: 527,
      QuestionPaperId: 79,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "SS",
      SubCategoryName: "6.Social Security",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [
        { AText: "Yes", Id: 5359 },
        { AText: "No", Id: 5360 },
      ],
      CategoryDesc: "EDCS",
      CategoryName: "Karmani V0.1",
      DisplaySequence: 13,
      Id: 2181,
      QText: "Do you have Insurance certificates",
      QuestionId: 590,
      QuestionPaperId: 79,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "SS",
      SubCategoryName: "6.Social Security",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [
        { AText: "Health", Id: 5361 },
        { AText: "Life", Id: 5362 },
        { AText: "Education", Id: 5363 },
        { AText: "Others ", Id: 5364 },
      ],
      CategoryDesc: "EDCS",
      CategoryName: "Karmani V0.1",
      DisplaySequence: 14,
      Id: 2182,
      QText: "Which of the following insurance do you have: ",
      QuestionId: 592,
      QuestionPaperId: 79,
      QuestionTypeName: "Multi Select",
      SubCategoryDesc: "SS",
      SubCategoryName: "6.Social Security",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [],
      CategoryDesc: "EDCS",
      CategoryName: "Karmani V0.1",
      DisplaySequence: 15,
      Id: 2193,
      QText: "If other insurance, specify",
      QuestionId: 596,
      QuestionPaperId: 79,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "SS",
      SubCategoryName: "6.Social Security",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [
        { AText: "Aadhar card ", Id: 5365 },
        { AText: "Voter ID", Id: 5366 },
        { AText: "Ration card", Id: 5367 },
        { AText: "Passport", Id: 5368 },
        { AText: "Disability card", Id: 5369 },
        { AText: "Pan card", Id: 5370 },
        { AText: "Driving License ", Id: 5371 },
        { AText: "Senior citizen card", Id: 5372 },
        { AText: "MGNREGA job card", Id: 5373 },
        { AText: "Caste certificate", Id: 5374 },
        { AText: "Birth certificate", Id: 5375 },
        { AText: "Bank passbook", Id: 5376 },
        { AText: "Others", Id: 5377 },
      ],
      CategoryDesc: "EDCS",
      CategoryName: "Karmani V0.1",
      DisplaySequence: 16,
      Id: 2183,
      QText: "Identity documents",
      QuestionId: 598,
      QuestionPaperId: 79,
      QuestionTypeName: "Multi Select",
      SubCategoryDesc: "SS",
      SubCategoryName: "6.Social Security",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [],
      CategoryDesc: "EDCS",
      CategoryName: "Karmani V0.1",
      DisplaySequence: 17,
      Id: 2194,
      QText: " if other Identity documents,specify",
      QuestionId: 608,
      QuestionPaperId: 79,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "SS",
      SubCategoryName: "6.Social Security",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [
        { AText: "MGNREGA job card", Id: 5378 },
        { AText: "Yashasvini card", Id: 5379 },
        { AText: "Manasvini card", Id: 5380 },
        { AText: "Maitri card", Id: 5381 },
        { AText: "Kissan credit card", Id: 5382 },
        { AText: "Union Membership card", Id: 5383 },
        { AText: "Cooperative Society card", Id: 5384 },
        { AText: "Self Help group card", Id: 5385 },
        { AText: "Welfare Scheme cards", Id: 5386 },
        { AText: "Government Health Scheme card", Id: 5387 },
        { AText: "Others specify ", Id: 5388 },
      ],
      CategoryDesc: "EDCS",
      CategoryName: "Karmani V0.1",
      DisplaySequence: 18,
      Id: 2184,
      QText: "Do you have any of these cards?",
      QuestionId: 609,
      QuestionPaperId: 79,
      QuestionTypeName: "Multi Select",
      SubCategoryDesc: "SS",
      SubCategoryName: "6.Social Security",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [],
      CategoryDesc: "EDCS",
      CategoryName: "Karmani V0.1",
      DisplaySequence: 19,
      Id: 2195,
      QText: "If other cards,specify",
      QuestionId: 619,
      QuestionPaperId: 79,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "SS",
      SubCategoryName: "6.Social Security",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [
        { AText: "Yes", Id: 5389 },
        { AText: "No", Id: 5390 },
      ],
      CategoryDesc: "EDCS",
      CategoryName: "Karmani V0.1",
      DisplaySequence: 20,
      Id: 2185,
      QText:
        "Have you changed your name & gender before Transgenders Protection of Rights Act 2019",
      QuestionId: 620,
      QuestionPaperId: 79,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "SS",
      SubCategoryName: "6.Social Security",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [
        { AText: "Yes", Id: 5391 },
        { AText: "No", Id: 5392 },
      ],
      CategoryDesc: "EDCS",
      CategoryName: "Karmani V0.1",
      DisplaySequence: 21,
      Id: 2186,
      QText:
        "If you changed the name and gender, did you do it through affidavit",
      QuestionId: 626,
      QuestionPaperId: 79,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "SS",
      SubCategoryName: "6.Social Security",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [
        { AText: "Yes", Id: 5393 },
        { AText: "No", Id: 5394 },
      ],
      CategoryDesc: "EDCS",
      CategoryName: "Karmani V0.1",
      DisplaySequence: 22,
      Id: 2187,
      QText: "Have you availed any Karnataka Government Scheme",
      QuestionId: 630,
      QuestionPaperId: 79,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "SS",
      SubCategoryName: "6.Social Security",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [
        { AText: "Transgender Rehabilitation Program", Id: 5395 },
        { AText: "Udyogini", Id: 5396 },
        { AText: "Samrudhi", Id: 5397 },
        { AText: "Mythri", Id: 5398 },
        { AText: "Housing Schemes", Id: 5399 },
        { AText: "Others", Id: 5400 },
      ],
      CategoryDesc: "EDCS",
      CategoryName: "Karmani V0.1",
      DisplaySequence: 23,
      Id: 2188,
      QText: "If yes, which Government Scheme please specify",
      QuestionId: 633,
      QuestionPaperId: 79,
      QuestionTypeName: "Multi Select",
      SubCategoryDesc: "SS",
      SubCategoryName: "6.Social Security",
    },
  ],
};

export default SocialSecurity;
