const SocialSecurity = {
  Id: 1,
  Name: "TG Social Security 1",
  QuestionCount: 152,
  EntityType: "SocialSecurity",
  Questions: [
    {
      AdditionalComment: false,
      AnswerChoices: ["Yes", "No"],
      AnswerChoices_KN:["ಹೌದು","ಇಲ್ಲ"],
      CategoryDesc: "Social Security",
      CategoryName: "Social Security",
      DisplaySequence: 147,
      Id: 147,
      QText: "Do you get pension?",
      QText_KN: "ನೀವು ಪಿಂಚಣಿ ಪಡೆಯುತ್ತೀರಾ?",
      QuestionId: 147,
      QuestionPaperId: 147,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Personal Details",
      SubCategoryName: "Personal Details",
    },
    {
      AdditionalComment: true,
      AdditionalQuestion:"If Others, specify",
      AnswerChoices: [
     "Indira Gandhi National Old Pension Scheme Mytri",
      "Disability pension", 
      "Sandhya suraksha",
     'Others'
      ],
      AnswerChoices_KN:[
      "ಇಂದಿರಾ ಗಾಂಧಿ ರಾಷ್ಟ್ರೀಯ ವೃದ್ದಾಪ್ಯ ಪಿಂಚಣಿ ಯೋಜನೆ",
      "ಮೈತ್ರಿ",
      "ವಿಕಲಚೇತನರ ಮಾಸಾಶನ",
      "ಸಂಧ್ಯಾ ಸುರಕ್ಷಾ",
      "ಇತರೆ",
      ],
      CategoryDesc: "Social Security",
      CategoryName: "Social Security",
      DisplaySequence: 148,
      Id: 148,
      QText: "If Yes, from which scheme?",
      QText_KN: "ಹಾಗಿದ್ದರೆ ಯಾವ ಯೋಜನೆಯಿಂದ?",
      QuestionId: 148,
      QuestionPaperId: 148,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Personal Details",
      SubCategoryName: "Personal Details",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [],
      CategoryDesc: "Social Security",
      CategoryName: "Social Security",
      DisplaySequence: 149,
      Id: 149,
      QText: "If Others, specify",
      QText_KN:"ಇತರೆಯಾದಲ್ಲಿ, ಸ್ಪಷ್ಟವಾಗಿ ನಮೂದಿಸಿ",
      QuestionId: 149,
      QuestionPaperId: 149,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Personal Details",
      SubCategoryName: "Personal Details",
    },
    {
      AdditionalComment: false,
      AnswerChoices: ["Yes","No"],
      AnswerChoices_KN:["ಹೌದು","ಇಲ್ಲ"],
      CategoryDesc: "Social Security",
      CategoryName: "Social Security",
      DisplaySequence: 150,
      Id: 150,
      QText: "Do you get ration?",
      QText_KN: "ನಿಮಗೆ ಪಡಿತರ ಸಿಗುತ್ತದೆಯೇ?",
      QuestionId: 150,
      QuestionPaperId: 150,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Personal Details",
      SubCategoryName: "Personal Details",
    },
    {
      AdditionalComment: true,
      AdditionalQuestion:"If others, specify",
      AnswerChoices: [
       "Antyodaya(AAY)",
       "PHH(BPL)",
       "NPHH(APL)",
       "Others"],
      AnswerChoices_KN:[
       "ಅಂತ್ಯೋದಯ(ಎ.ಎ.ವೈ)",
       "ಪಿ.ಹೆಚ್.ಹೆಚ್.(ಬಿ.ಪಿ.ಎಲ್.)",
       "ಎನ್.ಪಿ.ಹೆಚ್.ಹೆಚ್.(ಎ.ಪಿ.ಎಲ್)",
       "ಇತರೆ",
        ],
      CategoryDesc: "Social Security",
      CategoryName: "Social Security",
      DisplaySequence: 151,
      Id: 151,
      QText: "If Yes, from which scheme?",
      QText_KN: "ಹಾಗಿದ್ದರೆ ಯಾವ ಯೋಜನೆಯಿಂದ?",
      QuestionId: 151,
      QuestionPaperId: 151,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Personal Details",
      SubCategoryName: "Personal Details",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [],
      CategoryDesc: "Social Security",
      CategoryName: "Social Security",
      DisplaySequence: 152,
      Id: 152,
      QText: "If Others, specify",
        QText_KN:"ಇತರೆಯಾದಲ್ಲಿ, ಸ್ಪಷ್ಟವಾಗಿ ನಮೂದಿಸಿ",
      QuestionId: 152,
      QuestionPaperId: 152,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Personal Details",
      SubCategoryName: "Personal Details",
    },
    {
      AdditionalComment: false,
      AnswerChoices: ["Yes","No"],
      AnswerChoices_KN:["ಹೌದು","ಇಲ್ಲ"],
      CategoryDesc: "Social Security",
      CategoryName: "Social Security",
      DisplaySequence: 153,
      Id: 153,
      QText: "Have you received any support for business/employment?",
      QText_KN: "ವ್ಯಾಪಾರ/ಉದ್ಯೋಗಕ್ಕಾಗಿ ನೀವು ಯಾವುದೇ ಬೆಂಬಲವನ್ನು ಪಡೆದಿದ್ದೀರಾ?",
      QuestionId: 153,
      QuestionPaperId: 153,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Personal Details",
      SubCategoryName: "Personal Details",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [],
      CategoryDesc: "Social Security",
      CategoryName: "Social Security",
      DisplaySequence: 154,
      Id: 154,
      QText: "If Yes, from which scheme?",
      QText_KN: "ಹಾಗಿದ್ದರೆ ಯಾವ ಯೋಜನೆಯಿಂದ?",
      QuestionId: 154,
      QuestionPaperId: 154,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Personal Details",
      SubCategoryName: "Personal Details",
    },
    {
      AdditionalComment: false,
      AnswerChoices: ["Yes","No"],
      AnswerChoices_KN:["ಹೌದು","ಇಲ್ಲ"],
      CategoryDesc: "Social Security",
      CategoryName: "Social Security",
      DisplaySequence: 155,
      Id: 155,
      QText: "Have you received any support for education?",
      QText_KN: "ನೀವು ಶಿಕ್ಷಣಕ್ಕಾಗಿ ಯಾವುದೇ ಬೆಂಬಲವನ್ನು ಪಡೆದಿದ್ದೀರಾ?",
      QuestionId: 155,
      QuestionPaperId: 155,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Personal Details",
      SubCategoryName: "Personal Details",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [],
      CategoryDesc: "Social Security",
      CategoryName: "Social Security",
      DisplaySequence: 156,
      Id: 156,
      QText: "If Yes, from which scheme/scholarship?",
      QText_KN: "ನೀವು ಶಿಕ್ಷಣಕ್ಕಾಗಿ ಯಾವುದೇ ಬೆಂಬಲವನ್ನು ಪಡೆದಿದ್ದೀರಾ?",
      QuestionId: 156,
      QuestionPaperId: 156,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Personal Details",
      SubCategoryName: "Personal Details",
    },
    {
      AdditionalComment: false,
      AnswerChoices: ["Yes","No"],
      AnswerChoices_KN:["ಹೌದು","ಇಲ್ಲ"],
      CategoryDesc: "Social Security",
      CategoryName: "Social Security",
      DisplaySequence: 157,
      Id: 157,
      QText: "Do you have any caste certificate?",
      QText_KN: "ನಿಮ್ಮ ಬಳಿ ಜಾತಿ ಪ್ರಮಾಣ ಪತ್ರ ಇದೆಯೇ?",
      QuestionId: 157,
      QuestionPaperId: 157,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Personal Details",
      SubCategoryName: "Personal Details",
    },
    {
      AdditionalComment: false,
      AnswerChoices: ["Yes","No"],
      AnswerChoices_KN:["ಹೌದು","ಇಲ್ಲ"],
      CategoryDesc: "Social Security",
      CategoryName: "Social Security",
      DisplaySequence: 158,
      Id: 158,
      QText: "Do you have income certificate?",
      QText_KN: "ನಿಮ್ಮ ಬಳಿ ಆದಾಯ ಪ್ರಮಾಣ ಪತ್ರ ಇದೆಯೇ?",
      QuestionId: 158,
      QuestionPaperId: 158,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Personal Details",
      SubCategoryName: "Personal Details",
    },
    {
      AdditionalComment: false,
      AnswerChoices: ["Yes","No"],
      AnswerChoices_KN:["ಹೌದು","ಇಲ್ಲ"],
      CategoryDesc: "Social Security",
      CategoryName: "Social Security",
      DisplaySequence: 159,
      Id: 159,
      QText: "Do you have insurance certificates?",
      QText_KN: "ನೀವು ವಿಮಾ ಪ್ರಮಾಣಪತ್ರಗಳನ್ನು ಹೊಂದಿದ್ದೀರಾ?",
      QuestionId: 159,
      QuestionPaperId: 159,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Personal Details",
      SubCategoryName: "Personal Details",
    },
    {
      AdditionalComment: true,
      AdditionalQuestion:"If Others, specify",
      AnswerChoices: ["Health",
        "Life",
        "Education",
        "Others" ],
      AnswerChoices_KN:["ಆರೋಗ್ಯ",
         "ಜೀವನ",
         " ಶಿಕ್ಷಣ",
        "ಇತರೆ",
     ],
      CategoryDesc: "Social Security",
      CategoryName: "Social Security",
      DisplaySequence: 160,
      Id: 160,
      QText: "Which of the following insurance do you have?",
      QText_KN: "ಈ ಕೆಳಗಿನ ಯಾವ ವಿಮೆಯನ್ನು ನೀವು ಹೊಂದಿರುವಿರಿ?",
      QuestionId: 160,
      QuestionPaperId: 160,
      QuestionTypeName: "Multiple Select",
      SubCategoryDesc: "Personal Details",
      SubCategoryName: "Personal Details",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [],
      CategoryDesc: "Social Security",
      CategoryName: "Social Security",
      DisplaySequence: 161,
      Id: 161,
      QText: "If Others, specify",
        QText_KN:"ಇತರೆಯಾದಲ್ಲಿ, ಸ್ಪಷ್ಟವಾಗಿ ನಮೂದಿಸಿ",
      QuestionId: 161,
      QuestionPaperId: 161,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Personal Details",
      SubCategoryName: "Personal Details",
    },
    {
      AdditionalComment: true,
      AdditionalComment:"If Others, specify",
      AnswerChoices: ["Aadhar Card ",
        "Voter ID",
        "Ration Card",
        "Passport",
        "Disability card",
        "Pan Card",
        "Driving License" ,
        "Senior Citizen Card",
        "MGNREGA job card",
        "Caste certificate",
        "Birth certificate",
        "Bank passbook",
        "Others"],
      AnswerChoices_KN:[
      "ಆಧಾರ್ ಕಾರ್ಡ್",
      "ಮತದಾರರ ಗುರುತಿನ ಚೀಟಿ",
      "ಪಡಿತರ ಚೀಟಿ",
      "ಪಾಸ್ಪೋರ್ಟ್",
      "ವಿಕಲಚೇತನರ ಗುರುತಿನ ಚೀಟಿ",
      "ಪ್ಯಾನ್ ಕಾರ್ಡ್",
      "ಚಾಲನಾ ಪರವಾನಗಿ",
      "ಹಿರಿಯ ನಾಗರಿಕರ ಕಾರ್ಡ್",
      "MGNREGA ಜಾಬ್ ಕಾರ್ಡ್",
      "ಜಾತಿ ಪ್ರಮಾಣ ಪತ್ರ",
      "ಜನನ ಪ್ರಮಾಣಪತ್ರ",
      "ಬ್ಯಾಂಕ್ ಪಾಸ್ ಪುಸ್ತಕ",
      "ಇತರೆ",
    ],
      CategoryDesc: "Social Security",
      CategoryName: "Social Security",
      DisplaySequence: 162,
      Id: 162,
      QText: "Identity Documents",
      QText_KN: "ಗುರುತಿನ ದಾಖಲೆಗಳು",
      QuestionId: 162,
      QuestionPaperId: 162,
      QuestionTypeName: "Multiple Select",
      SubCategoryDesc: "Personal Details",
      SubCategoryName: "Personal Details",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [],
      CategoryDesc: "Social Security",
      CategoryName: "Social Security",
      DisplaySequence: 163,
      Id: 163,
      QText: "If Others, specify",
        QText_KN:"ಇತರೆಯಾದಲ್ಲಿ, ಸ್ಪಷ್ಟವಾಗಿ ನಮೂದಿಸಿ",
      QuestionId: 163,
      QuestionPaperId: 163,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Personal Details",
      SubCategoryName: "Personal Details",
    },
    {
      AdditionalComment: true,
      AdditionalQuestion:"If Others, specify",
      AnswerChoices: [
        "MGNREGA job card",
        "Yashasvini card",
        "Manasvini card",
        "Maitri Card",
        "Kissan credit card",
        "Union Membership card",
        "Cooperative Society Card",
        "Self Help group card",
        "Welfare Scheme cards",
        "Government Health Scheme card",
        "Others Specify",
        "None"
      ],
      AnswerChoices_KN:[
      "MGNREGA ಜಾಬ್ ಕಾರ್ಡ್",
      "ಯಶಸ್ವಿನಿ ಕಾರ್ಡ್",
      "ಮನಸ್ವಿನಿ ಕಾರ್ಡ್",
      "ಮೈತ್ರಿ ಕಾರ್ಡ್",
      "ಕಿಸ್ಸಾನ್ ಕ್ರೆಡಿಟ್ ಕಾರ್ಡ್",
      "ಯೂನಿಯನ್ ಸದಸ್ಯತ್ವ ಕಾರ್ಡ್",
      "ಸಹಕಾರ ಸಂಘದ ಕಾರ್ಡ್",
      "ಸ್ವ ಸಹಾಯ ಗುಂಪು ಕಾರ್ಡ್",
      "ಕಲ್ಯಾಣ ಯೋಜನೆ ಕಾರ್ಡ್",
    ],
      CategoryDesc: "Social Security",
      CategoryName: "Social Security",
      DisplaySequence: 164,
      Id: 164,
      QText: "Do you have any of these Cards?",
      QText_KN: "ಈ ಕಾರ್ಡ್‌ಗಳಲ್ಲಿ ಯಾವುದಾದರೂ ನಿಮ್ಮ ಬಳಿ ಇದೆಯೇ?",
      QuestionId: 164,
      QuestionPaperId: 164,
      QuestionTypeName: "Multiple Select",
      SubCategoryDesc: "Personal Details",
      SubCategoryName: "Personal Details",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [],
      CategoryDesc: "Social Security",
      CategoryName: "Social Security",
      DisplaySequence: 165,
      Id: 165,
      QText: "If Others, specify",
        QText_KN:"ಇತರೆಯಾದಲ್ಲಿ, ಸ್ಪಷ್ಟವಾಗಿ ನಮೂದಿಸಿ",
      QuestionId: 165,
      QuestionPaperId: 165,
      QuestionTypeName: "Descriptive",
      SubCategoryDesc: "Personal Details",
      SubCategoryName: "Personal Details",
    },
    {
      AdditionalComment: false,
      AnswerChoices: ["Yes","No"],
      AnswerChoices_KN:["ಹೌದು","ಇಲ್ಲ"],
      CategoryDesc: "Social Security",
      CategoryName: "Social Security",
      DisplaySequence: 166,
      Id: 166,
      QText:
        "Have you changed your name & gender before transgender protection of rights act 2019?",
        QText_KN: "2019 ರ ಹಕ್ಕುಗಳ ಟ್ರಾನ್ಸ್‌ಜೆಂಡರ್ ರಕ್ಷಣೆಯ ಮೊದಲು ನೀವು ನಿಮ್ಮ ಹೆಸರು ಮತ್ತು ಲಿಂಗವನ್ನು ಬದಲಾಯಿಸಿದ್ದೀರಾ?",
      QuestionId: 166,
      QuestionPaperId: 166,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Personal Details",
      SubCategoryName: "Personal Details",
    },
    {
      AdditionalComment: false,
      AnswerChoices: ["Yes","No"],
      AnswerChoices_KN:["ಹೌದು","ಇಲ್ಲ"],
      CategoryDesc: "Social Security",
      CategoryName: "Social Security",
      DisplaySequence: 167,
      Id: 167,
      QText: "If Yes, did you do it through  affidavit?",
      QText_KN: "ಹೌದು ಎಂದಾದರೆ ನೀವು ಅದನ್ನು ಅಫಿಡವಿಟ್ ಮೂಲಕ ಮಾಡಿದ್ದೀರಾ?",
      QuestionId: 167,
      QuestionPaperId: 167,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Personal Details",
      SubCategoryName: "Personal Details",
    },
    {
      AdditionalComment: false,
      AnswerChoices: ["Yes","No"],
      AnswerChoices_KN:["ಹೌದು","ಇಲ್ಲ"],
      CategoryDesc: "Social Security",
      CategoryName: "Social Security",
      DisplaySequence: 168,
      Id: 168,
      QText: "Have you availed any Karnataka government scheme?",
      QText_KN: "ನಿಮ್ಮಲ್ಲಿ ಯಾವುದಾದರೂ ಕರ್ನಾಟಕ ಸರ್ಕಾರದ ಯೋಜನೆ ಇದೆಯೇ?",
      QuestionId: 168,
      QuestionPaperId: 168,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Personal Details",
      SubCategoryName: "Personal Details",
    },
    {
      AdditionalComment: false,
      AnswerChoices: [
        "Transgender Rehabilitation Program",
        "Udyogini",
        'Samrudhi',
        "Mythri",
        "Housing Schemes",
       "Others"],
       AnswerChoices_KN:[
       "ಲಿಂಗತ್ವ ಅಲ್ಪಸಂಖ್ಯಾತರ ಪುನರ್ವಸತಿ ಯೋಜನೆ",
       "ಉದ್ಯೋಗಿನಿ",
       "ಸಮೃದ್ಧಿ",
       "ಮೈತ್ರಿ",
       "ವಸತಿ ಯೋಜನೆಗಳು",
       "ಇತರೆ",
       ],
      CategoryDesc: "Social Security",
      CategoryName: "Social Security",
      DisplaySequence: 169,
      Id: 169,
      QText: "If Yes, which please specify?",
      QText_KN: "ಹೌದಾದರೆ ದಯವಿಟ್ಟು ಯಾವುದನ್ನು ನಿರ್ದಿಷ್ಟಪಡಿಸಿ?",
      QuestionId: 169,
      QuestionPaperId: 169,
      QuestionTypeName: "Single Select",
      SubCategoryDesc: "Personal Details",
      SubCategoryName: "Personal Details",
    },
  ],
};

export default SocialSecurity;
